In [1]:
import json
import pickle
from dotenv import load_dotenv
from huggingface_hub import login
import pandas as pd
import penman
import torch
from torch_geometric.transforms import RemoveDuplicatedEdges

/Users/khatwans/Downloads/RuleSpect/newEnv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
data_list = []

with open("../alignedEmbeddings.jsonl", "r") as f:
    for line in f:
        try:
            json_object = json.loads(line)
            data_list.append(json_object)
        except json.JSONDecodeError:
            # Handle cases where a line might be empty or malformed
            continue

In [6]:
len(data_list)

476

In [9]:
data_list[0].keys()

dict_keys(['lpp_1943.1'])

In [185]:
list(data_list[0].keys())

['lpp_1943.1']

In [7]:
train_data = []

with open("./UMRDataset/raw/train_data.json", "r") as f:
    train_data = json.load(f)

In [10]:
# train_data = []

with open("./UMRDataset/raw/splits.json", "r") as f:
    splits = json.load(f)

In [12]:
splits

{'train': ['wb.p2.5_c2e_0037.8',
  'lpp_1943.723',
  'lpp_1943.631',
  'bolt-eng-DF-201-185510-351190_0311.4',
  'lpp_1943.668',
  'lpp_1943.94',
  'lpp_1943.64',
  'lpp_1943.33',
  'lpp_1943.619',
  'bolt-eng-DF-170-181103-8889674_0058.2',
  'minecraft-4-4-table2-b29-a8_1167.14',
  'lpp_1943.44',
  'lpp_1943.126',
  'bolt-eng-DF-170-181103-8889674_0058.6',
  'lpp_1943.133',
  'lpp_1943.746',
  'minecraft-4-4-table2-b29-a8_1167.19',
  'bolt-eng-DF-170-181122-8787903_0048.13',
  'lpp_1943.657',
  'lpp_1943.115',
  'lpp_1943.720',
  'lpp_1943.86',
  'bolt-eng-DF-170-181103-8889674_0059.13',
  'bolt-eng-DF-170-181105-8850361_0028.19',
  'bolt-eng-DF-201-185510-351190_0310.6',
  'lpp_1943.747',
  'wb.p2.5_c2e_0046.3',
  'lpp_1943.742',
  'web1-eng-DF-241-201379-5514596_0001.2',
  'minecraft-4-6-3d-triangle_1245.7',
  'lpp_1943.630',
  'minecraft-4-6-3d-triangle_1245.25',
  'lpp_1943.728',
  'bolt-eng-DF-201-185510-351190_0310.1',
  'bolt-eng-DF-170-181103-8886126_0017.1',
  'lpp_1943.30',
  'bolt-eng-DF-170-181105-8850361_0028.26',
  'lpp_1943.106',
  'lpp_1943.693',
  'lpp_1943.710',
  'bolt-eng-DF-170-181103-8889674_0059.16',
  'bolt-eng-DF-170-181105-8850361_0028.17',
  'lpp_1943.124',
  'lpp_1943.55',
  'lpp_1943.732',
  'lpp_1943.613',
  'lpp_1943.617',
  'bolt-eng-DF-170-181103-8886126_0017.4',
  'lpp_1943.624',
  'lpp_1943.683',
  'lpp_1943.81',
  'lpp_1943.651',
  'minecraft-4-6-3d-triangle_1245.24',
  'minecraft-4-6-3d-triangle_1245.28',
  'minecraft-4-4-table2-b29-a8_1167.13',
  'wb.p2.5_c2e_0037.1',
  'minecraft-4-4-table2-b29-a8_1167.23',
  'bolt-eng-DF-170-181105-8850361_0028.22',
  'lpp_1943.735',
  'minecraft-4-6-3d-triangle_1245.4',
  'lpp_1943.662',
  'lpp_1943.650',
  'lpp_1943.722',
  'lpp_1943.127',
  'bolt-eng-DF-170-181105-8850361_0028.28',
  'bolt-eng-DF-201-185510-351190_0310.13',
  'bolt-eng-DF-170-181103-8883574_0186.1',
  'lpp_1943.77',
  'bolt-eng-DF-170-181105-8850361_0028.31',
  'lpp_1943.724',
  'minecraft-4-4-table2-b29-a8_1167.2',
  'bolt-eng-DF-170-181103-8889674_0058.1',
  'lpp_1943.140',
  'bolt-eng-DF-201-185510-351190_0310.8',
  'lpp_1943.31',
  'lpp_1943.97',
  'lpp_1943.751',
  'lpp_1943.138',
  'wb.p2.5_c2e_0037.11',
  'lpp_1943.75',
  'wb.p2.5_c2e_0069.3',
  'minecraft-4-4-table2-b29-a8_1167.12',
  'lpp_1943.99',
  'lpp_1943.26',
  'bolt-eng-DF-170-181105-8850361_0028.32',
  'lpp_1943.66',
  'bolt-eng-DF-170-181122-8787903_0048.15',
  'lpp_1943.120',
  'lpp_1943.689',
  'lpp_1943.677',
  'minecraft-4-6-3d-triangle_1245.6',
  'bolt-eng-DF-170-181105-8850361_0028.27',
  'lpp_1943.46',
  'lpp_1943.703',
  'wb.p2.5_c2e_0046.9',
  'bolt-eng-DF-170-181122-8787903_0048.8',
  'bolt-eng-DF-170-181103-8886126_0017.2',
  'lpp_1943.89',
  'wb.p2.5_c2e_0046.6',
  'lpp_1943.87',
  'lpp_1943.612',
  'lpp_1943.37',
  'minecraft-4-6-3d-triangle_1245.18',
  'lpp_1943.88',
  'minecraft-4-4-table2-b29-a8_1167.11',
  'web1-eng-DF-241-201379-5514596_0003.2',
  'wb.p2.5_c2e_0069.1',
  'minecraft-4-4-table2-b29-a8_1167.21',
  'lpp_1943.73',
  'minecraft-4-4-table2-b29-a8_1167.3',
  'bolt-eng-DF-170-181105-8850361_0028.33',
  'lpp_1943.59',
  'bolt-eng-DF-170-181103-8886126_0017.7',
  'bolt-eng-DF-201-185510-351190_0310.4',
  'lpp_1943.28',
  'lpp_1943.673',
  'lpp_1943.669',
  'lpp_1943.47',
  'lpp_1943.745',
  'lpp_1943.734',
  'lpp_1943.35',
  'minecraft-4-6-3d-triangle_1245.19',
  'lpp_1943.733',
  'bolt-eng-DF-201-185510-351190_0310.17',
  'lpp_1943.739',
  'lpp_1943.50',
  'minecraft-4-6-3d-triangle_1245.26',
  'lpp_1943.65',
  'lpp_1943.698',
  'wb.p2.5_c2e_0046.10',
  'bolt-eng-DF-170-181105-8850361_0028.25',
  'minecraft-4-6-3d-triangle_1245.10',
  'lpp_1943.706',
  'bolt-eng-DF-170-181105-8850361_0028.15',
  'lpp_1943.738',
  'bolt-eng-DF-170-181122-8787903_0048.7',
  'wb.p2.5_c2e_0037.5',
  'minecraft-4-6-3d-triangle_1245.16',
  'lpp_1943.67',
  'bolt-eng-DF-170-181103-8891686_0020.16',
  'bolt-eng-DF-170-181122-8787903_0049.6',
  'minecraft-4-4-table2-b29-a8_1167.7',
  'lpp_1943.32',
  'lpp_1943.92',
  'lpp_1943.52',
  'lpp_1943.737',
  'lpp_1943.84',
  'bolt-eng-DF-170-181103-8892003_0048.8',
  'bolt-eng-DF-170-181122-8787903_0048.12',
  'lpp_1943.79',
  'lpp_1943.632',
  'lpp_1943.70',
  'lpp_1943.113',
  'lpp_1943.48',
  'lpp_1943.119',
  'bolt-eng-DF-170-181122-8787903_0048.9',
  'lpp_1943.719',
  'lpp_1943.653',
  'lpp_1943.652',
  'minecraft-4-4-table2-b29-a8_1167.27',
  'lpp_1943.610',
  'bolt-eng-DF-170-181105-8850361_0028.23',
  'lpp_1943.727',
  'lpp_1943.715',
  'lpp_1943.53',
  'lpp_1943.96',
  'wb.p2.5_c2e_0037.4',
  'lpp_1943.670',
  'minecraft-4-6-3d-triangle_1245.21',
  'lpp_1943.680',
  'wb.p2.5_c2e_0037.6',
  'wb.p2.5_c2e_0046.5',
  'lpp_1943.660',
  'lpp_1943.604',
  'bolt-eng-DF-170-181122-8787903_0048.3',
  'bolt-eng-DF-170-181122-8787903_0049.1',
  'bolt-eng-DF-201-185510-351190_0310.2',
  'lpp_1943.129',
  'lpp_1943.136',
  'lpp_1943.623',
  'bolt-eng-DF-170-181105-8850361_0028.18',
  'wb.p2.5_c2e_0037.2',
  'bolt-eng-DF-201-185510-351190_0310.11',
  'bolt-eng-DF-170-181103-8889674_0059.15',
  'lpp_1943.63',
  'lpp_1943.39',
  'lpp_1943.743',
  'lpp_1943.749',
  'lpp_1943.649',
  'lpp_1943.69',
  'lpp_1943.659',
  'lpp_1943.125',
  'wb.p2.5_c2e_0069.4',
  'minecraft-4-6-3d-triangle_1245.23',
  'lpp_1943.109',
  'minecraft-4-6-3d-triangle_1245.3',
  'lpp_1943.633',
  'minecraft-4-6-3d-triangle_1245.12',
  'lpp_1943.655',
  'bolt-eng-DF-170-181122-8787903_0048.5',
  'bolt-eng-DF-170-181122-8787903_0049.3',
  'wb.p2.5_c2e_0037.3',
  'lpp_1943.100',
  'bolt-eng-DF-170-181103-8886126_0017.5',
  'lpp_1943.42',
  'lpp_1943.23',
  'lpp_1943.615',
  'bolt-eng-DF-170-181122-8787903_0049.4',
  'lpp_1943.114',
  'lpp_1943.43',
  'minecraft-4-4-table2-b29-a8_1167.1',
  'bolt-eng-DF-201-185510-351190_0311.5',
  'lpp_1943.711',
  'minecraft-4-6-3d-triangle_1245.13',
  'bolt-eng-DF-170-181122-8787903_0048.10',
  'bolt-eng-DF-170-181103-8889674_0058.7',
  'minecraft-4-4-table2-b29-a8_1167.25',
  'lpp_1943.130',
  'lpp_1943.80',
  'wb.p2.5_c2e_0037.10',
  'lpp_1943.626',
  'minecraft-4-6-3d-triangle_1245.32',
  'bolt-eng-DF-170-181103-8892003_0049.2',
  'lpp_1943.629',
  'lpp_1943.57',
  'bolt-eng-DF-170-181103-8891686_0020.15',
  'lpp_1943.679',
  'lpp_1943.132',
  'lpp_1943.620',
  'lpp_1943.107',
  'bolt-eng-DF-170-181103-8889674_0058.5',
  'lpp_1943.691',
  'lpp_1943.40',
  'wb.p2.5_c2e_0046.1',
  'lpp_1943.714',
  'lpp_1943.609',
  'lpp_1943.725',
  'wb.p2.5_c2e_0037.7',
  'bolt-eng-DF-170-181122-8787903_0048.11',
  'lpp_1943.105',
  'lpp_1943.54',
  'minecraft-4-4-table2-b29-a8_1167.24',
  'minecraft-4-6-3d-triangle_1245.17',
  'bolt-eng-DF-201-185510-351190_0310.35',
  'lpp_1943.729',
  'lpp_1943.694',
  'bolt-eng-DF-201-185510-351190_0310.7',
  'lpp_1943.654',
  'minecraft-4-6-3d-triangle_1245.31',
  'bolt-eng-DF-201-185510-351190_0310.14',
  'lpp_1943.667',
  'lpp_1943.707',
  'minecraft-4-6-3d-triangle_1245.11',
  'bolt-eng-DF-170-181122-8787903_0049.2',
  'wb.p2.5_c2e_0046.7',
  'bolt-eng-DF-170-181103-8892003_0048.9',
  'lpp_1943.135',
  'minecraft-4-4-table2-b29-a8_1167.4',
  'lpp_1943.713',
  'lpp_1943.672',
  'lpp_1943.51'],
 'val': ['bolt-eng-DF-170-181105-8850361_0028.29',
  'lpp_1943.78',
  'bolt-eng-DF-170-181122-8787903_0048.4',
  'minecraft-4-4-table2-b29-a8_1167.16',
  'lpp_1943.621',
  'minecraft-4-4-table2-b29-a8_1167.20',
  'lpp_1943.74',
  'wb.p2.5_c2e_0069.2',
  'bolt-eng-DF-170-181103-8892003_0048.7',
  'lpp_1943.118',
  'lpp_1943.752',
  'wb.p2.5_c2e_0037.9',
  'wb.p2.5_c2e_0046.4',
  'lpp_1943.678',
  'lpp_1943.60',
  'minecraft-4-6-3d-triangle_1245.1',
  'bolt-eng-DF-201-185510-351190_0310.12',
  'bolt-eng-DF-170-181103-8892003_0049.1',
  'DF-170-181110-876_5210.10',
  'lpp_1943.131',
  'bolt-eng-DF-170-181105-8850361_0028.30',
  'bolt-eng-DF-201-185510-351190_0311.2',
  'minecraft-4-6-3d-triangle_1245.27',
  'lpp_1943.674',
  'bolt-eng-DF-170-181122-8787903_0049.5',
  'bolt-eng-DF-201-185510-351190_0311.1',
  'bolt-eng-DF-170-181103-8886126_0017.6',
  'lpp_1943.717',
  'lpp_1943.700',
  'minecraft-4-6-3d-triangle_1245.20',
  'lpp_1943.704',
  'lpp_1943.663',
  'bolt-eng-DF-170-181103-8886126_0017.8',
  'lpp_1943.726',
  'lpp_1943.38',
  'lpp_1943.614',
  'web1-eng-DF-241-201379-5514596_0001.1',
  'lpp_1943.627',
  'minecraft-4-4-table2-b29-a8_1167.6',
  'bolt-eng-DF-170-181105-8850361_0028.21',
  'lpp_1943.622',
  'lpp_1943.675',
  'lpp_1943.49',
  'lpp_1943.29',
  'lpp_1943.618',
  'bolt-eng-DF-201-185510-351190_0311.6',
  'lpp_1943.628',
  'lpp_1943.61',
  'lpp_1943.83',
  'minecraft-4-6-3d-triangle_1245.9',
  'lpp_1943.709',
  'bolt-eng-DF-201-185510-351190_0310.5',
  'lpp_1943.41',
  'lpp_1943.62',
  'minecraft-4-6-3d-triangle_1245.30',
  'lpp_1943.72'],
 'test': ['bolt-eng-DF-170-181105-8850361_0028.20',
  'minecraft-4-4-table2-b29-a8_1167.22',
  'lpp_1943.56',
  'lpp_1943.696',
  'bolt-eng-DF-201-185510-351190_0310.33',
  'bolt-eng-DF-170-181103-8889674_0059.14',
  'wb.p2.5_c2e_0046.8',
  'bolt-eng-DF-201-185510-351190_0310.9',
  'lpp_1943.750',
  'lpp_1943.748',
  'lpp_1943.740',
  'lpp_1943.616',
  'lpp_1943.76',
  'lpp_1943.21',
  'lpp_1943.85',
  'lpp_1943.671',
  'lpp_1943.90',
  'lpp_1943.665',
  'bolt-eng-DF-170-181103-8889674_0058.3',
  'minecraft-4-6-3d-triangle_1245.15',
  'lpp_1943.27',
  'lpp_1943.658',
  'lpp_1943.607',
  'lpp_1943.58',
  'lpp_1943.34',
  'lpp_1943.690',
  'lpp_1943.753',
  'lpp_1943.699',
  'lpp_1943.625',
  'lpp_1943.24',
  'bolt-eng-DF-170-181122-8787903_0048.2',
  'bolt-eng-DF-170-181103-8892003_0049.3',
  'bolt-eng-DF-170-181122-8787903_0048.1',
  'lpp_1943.128',
  'minecraft-4-4-table2-b29-a8_1167.17',
  'lpp_1943.22',
  'lpp_1943.104',
  'bolt-eng-DF-201-185510-351190_0311.3',
  'lpp_1943.25',
  'lpp_1943.666',
  'bolt-eng-DF-170-181122-8787903_0049.7',
  'minecraft-4-6-3d-triangle_1245.5',
  'lpp_1943.611',
  'lpp_1943.12',
  'lpp_1943.112',
  'bolt-eng-DF-201-185510-351190_0310.16',
  'bolt-eng-DF-201-185510-351190_0310.10',
  'lpp_1943.101',
  'bolt-eng-DF-170-181103-8892003_0048.6',
  'lpp_1943.102',
  'bolt-eng-DF-170-181122-8787903_0048.6',
  'lpp_1943.121',
  'lpp_1943.716',
  'bolt-eng-DF-170-181103-8889674_0058.4',
  'lpp_1943.139',
  'minecraft-4-4-table2-b29-a8_1167.15']}

In [8]:
train_data.keys()

dict_keys(['lpp_1943.12', 'lpp_1943.21', 'lpp_1943.22', 'lpp_1943.23', 'lpp_1943.24', 'lpp_1943.25', 'lpp_1943.26', 'lpp_1943.27', 'lpp_1943.28', 'lpp_1943.29', 'lpp_1943.30', 'lpp_1943.31', 'lpp_1943.32', 'lpp_1943.33', 'lpp_1943.34', 'lpp_1943.35', 'lpp_1943.604', 'lpp_1943.607', 'lpp_1943.609', 'lpp_1943.610', 'lpp_1943.611', 'lpp_1943.612', 'lpp_1943.613', 'lpp_1943.614', 'lpp_1943.615', 'lpp_1943.616', 'lpp_1943.617', 'lpp_1943.618', 'lpp_1943.619', 'lpp_1943.620', 'lpp_1943.621', 'lpp_1943.622', 'lpp_1943.623', 'lpp_1943.624', 'lpp_1943.625', 'lpp_1943.626', 'lpp_1943.627', 'lpp_1943.628', 'lpp_1943.629', 'lpp_1943.630', 'lpp_1943.631', 'lpp_1943.632', 'lpp_1943.633', 'lpp_1943.649', 'lpp_1943.650', 'lpp_1943.651', 'lpp_1943.652', 'lpp_1943.653', 'lpp_1943.654', 'lpp_1943.655', 'lpp_1943.657', 'lpp_1943.658', 'lpp_1943.659', 'lpp_1943.660', 'lpp_1943.662', 'lpp_1943.663', 'lpp_1943.665', 'lpp_1943.666', 'lpp_1943.667', 'lpp_1943.668', 'lpp_1943.669', 'lpp_1943.670', 'lpp_1943.671', 'lpp_1943.672', 'lpp_1943.673', 'lpp_1943.674', 'lpp_1943.675', 'lpp_1943.677', 'lpp_1943.678', 'lpp_1943.679', 'lpp_1943.680', 'lpp_1943.683', 'lpp_1943.689', 'lpp_1943.690', 'lpp_1943.691', 'lpp_1943.693', 'lpp_1943.694', 'lpp_1943.696', 'lpp_1943.698', 'lpp_1943.699', 'lpp_1943.700', 'lpp_1943.703', 'lpp_1943.704', 'lpp_1943.706', 'lpp_1943.707', 'lpp_1943.709', 'lpp_1943.710', 'lpp_1943.711', 'lpp_1943.713', 'lpp_1943.714', 'lpp_1943.715', 'lpp_1943.716', 'lpp_1943.717', 'lpp_1943.719', 'lpp_1943.720', 'lpp_1943.722', 'lpp_1943.723', 'lpp_1943.724', 'lpp_1943.725', 'lpp_1943.726', 'lpp_1943.727', 'lpp_1943.728', 'lpp_1943.729', 'lpp_1943.732', 'lpp_1943.733', 'lpp_1943.734', 'lpp_1943.735', 'lpp_1943.737', 'lpp_1943.738', 'lpp_1943.739', 'lpp_1943.740', 'lpp_1943.742', 'lpp_1943.743', 'lpp_1943.745', 'lpp_1943.746', 'lpp_1943.747', 'lpp_1943.748', 'lpp_1943.749', 'lpp_1943.750', 'lpp_1943.751', 'lpp_1943.752', 'lpp_1943.753', 'lpp_1943.37', 'lpp_1943.38', 'lpp_1943.39', 'lpp_1943.40', 'lpp_1943.41', 'lpp_1943.42', 'lpp_1943.43', 'lpp_1943.44', 'lpp_1943.46', 'lpp_1943.47', 'lpp_1943.48', 'lpp_1943.49', 'lpp_1943.50', 'lpp_1943.51', 'lpp_1943.52', 'lpp_1943.53', 'lpp_1943.54', 'lpp_1943.55', 'lpp_1943.56', 'lpp_1943.57', 'lpp_1943.58', 'lpp_1943.59', 'lpp_1943.60', 'lpp_1943.61', 'lpp_1943.62', 'lpp_1943.63', 'lpp_1943.64', 'lpp_1943.65', 'lpp_1943.66', 'lpp_1943.67', 'lpp_1943.69', 'lpp_1943.70', 'lpp_1943.72', 'lpp_1943.73', 'lpp_1943.74', 'lpp_1943.75', 'lpp_1943.76', 'lpp_1943.77', 'lpp_1943.78', 'lpp_1943.79', 'lpp_1943.80', 'lpp_1943.81', 'lpp_1943.83', 'lpp_1943.84', 'lpp_1943.85', 'lpp_1943.86', 'lpp_1943.87', 'lpp_1943.88', 'lpp_1943.89', 'lpp_1943.90', 'lpp_1943.92', 'lpp_1943.94', 'lpp_1943.96', 'lpp_1943.97', 'lpp_1943.99', 'lpp_1943.100', 'lpp_1943.101', 'lpp_1943.102', 'lpp_1943.104', 'lpp_1943.105', 'lpp_1943.106', 'lpp_1943.107', 'lpp_1943.109', 'lpp_1943.112', 'lpp_1943.113', 'lpp_1943.114', 'lpp_1943.115', 'lpp_1943.118', 'lpp_1943.119', 'lpp_1943.120', 'lpp_1943.121', 'lpp_1943.124', 'lpp_1943.125', 'lpp_1943.126', 'lpp_1943.127', 'lpp_1943.128', 'lpp_1943.129', 'lpp_1943.130', 'lpp_1943.131', 'lpp_1943.132', 'lpp_1943.133', 'lpp_1943.135', 'lpp_1943.136', 'lpp_1943.138', 'lpp_1943.139', 'lpp_1943.140', 'wb.p2.5_c2e_0037.1', 'wb.p2.5_c2e_0037.2', 'wb.p2.5_c2e_0037.3', 'wb.p2.5_c2e_0037.4', 'wb.p2.5_c2e_0037.5', 'wb.p2.5_c2e_0037.6', 'wb.p2.5_c2e_0037.7', 'wb.p2.5_c2e_0037.8', 'wb.p2.5_c2e_0037.9', 'wb.p2.5_c2e_0037.10', 'wb.p2.5_c2e_0037.11', 'wb.p2.5_c2e_0046.1', 'wb.p2.5_c2e_0046.3', 'wb.p2.5_c2e_0046.4', 'wb.p2.5_c2e_0046.5', 'wb.p2.5_c2e_0046.6', 'wb.p2.5_c2e_0046.7', 'wb.p2.5_c2e_0046.8', 'wb.p2.5_c2e_0046.9', 'wb.p2.5_c2e_0046.10', 'wb.p2.5_c2e_0069.1', 'wb.p2.5_c2e_0069.2', 'wb.p2.5_c2e_0069.3', 'wb.p2.5_c2e_0069.4', 'minecraft-4-6-3d-triangle_1245.1', 'minecraft-4-6-3d-triangle_1245.3', 'minecraft-4-6-3d-triangle_1245.4', 'minecraft-4-6-3d-triangle_1245.5', 'minecraft-4-6-3d-triangle_1245.6', 'minecraft-4-6-3d-triangle_1245.7', 'minecraft-4-6-3d-triangle_1245.9', 'minecraft-4-6-3d-triangle_1245.10', 'minecraft-4-6-3d-triangle_1245.11', 'minecraft-4-6-3d-triangle_1245.12', 'minecraft-4-6-3d-triangle_1245.13', 'minecraft-4-6-3d-triangle_1245.15', 'minecraft-4-6-3d-triangle_1245.16', 'minecraft-4-6-3d-triangle_1245.17', 'minecraft-4-6-3d-triangle_1245.18', 'minecraft-4-6-3d-triangle_1245.19', 'minecraft-4-6-3d-triangle_1245.20', 'minecraft-4-6-3d-triangle_1245.21', 'minecraft-4-6-3d-triangle_1245.23', 'minecraft-4-6-3d-triangle_1245.24', 'minecraft-4-6-3d-triangle_1245.25', 'minecraft-4-6-3d-triangle_1245.26', 'minecraft-4-6-3d-triangle_1245.27', 'minecraft-4-6-3d-triangle_1245.28', 'minecraft-4-6-3d-triangle_1245.30', 'minecraft-4-6-3d-triangle_1245.31', 'minecraft-4-6-3d-triangle_1245.32', 'minecraft-4-4-table2-b29-a8_1167.1', 'minecraft-4-4-table2-b29-a8_1167.2', 'minecraft-4-4-table2-b29-a8_1167.3', 'minecraft-4-4-table2-b29-a8_1167.4', 'minecraft-4-4-table2-b29-a8_1167.6', 'minecraft-4-4-table2-b29-a8_1167.7', 'minecraft-4-4-table2-b29-a8_1167.11', 'minecraft-4-4-table2-b29-a8_1167.12', 'minecraft-4-4-table2-b29-a8_1167.13', 'minecraft-4-4-table2-b29-a8_1167.14', 'minecraft-4-4-table2-b29-a8_1167.15', 'minecraft-4-4-table2-b29-a8_1167.16', 'minecraft-4-4-table2-b29-a8_1167.17', 'minecraft-4-4-table2-b29-a8_1167.19', 'minecraft-4-4-table2-b29-a8_1167.20', 'minecraft-4-4-table2-b29-a8_1167.21', 'minecraft-4-4-table2-b29-a8_1167.22', 'minecraft-4-4-table2-b29-a8_1167.23', 'minecraft-4-4-table2-b29-a8_1167.24', 'minecraft-4-4-table2-b29-a8_1167.25', 'minecraft-4-4-table2-b29-a8_1167.27', 'bolt-eng-DF-170-181103-8892003_0049.1', 'bolt-eng-DF-170-181103-8892003_0049.2', 'bolt-eng-DF-170-181103-8892003_0049.3', 'bolt-eng-DF-170-181122-8787903_0048.1', 'bolt-eng-DF-170-181122-8787903_0048.2', 'bolt-eng-DF-170-181122-8787903_0048.3', 'bolt-eng-DF-170-181122-8787903_0048.4', 'bolt-eng-DF-170-181122-8787903_0048.5', 'bolt-eng-DF-170-181122-8787903_0048.6', 'bolt-eng-DF-170-181122-8787903_0048.7', 'bolt-eng-DF-170-181122-8787903_0048.8', 'bolt-eng-DF-170-181122-8787903_0048.9', 'bolt-eng-DF-170-181122-8787903_0048.10', 'bolt-eng-DF-170-181122-8787903_0048.11', 'bolt-eng-DF-170-181122-8787903_0048.12', 'bolt-eng-DF-170-181122-8787903_0048.13', 'bolt-eng-DF-170-181122-8787903_0048.15', 'bolt-eng-DF-170-181122-8787903_0049.1', 'bolt-eng-DF-170-181122-8787903_0049.2', 'bolt-eng-DF-170-181122-8787903_0049.3', 'bolt-eng-DF-170-181122-8787903_0049.4', 'bolt-eng-DF-170-181122-8787903_0049.5', 'bolt-eng-DF-170-181122-8787903_0049.6', 'bolt-eng-DF-170-181122-8787903_0049.7', 'bolt-eng-DF-170-181103-8892003_0048.6', 'bolt-eng-DF-170-181103-8892003_0048.7', 'bolt-eng-DF-170-181103-8892003_0048.8', 'bolt-eng-DF-170-181103-8892003_0048.9', 'web1-eng-DF-241-201379-5514596_0003.2', 'bolt-eng-DF-170-181103-8883574_0186.1', 'bolt-eng-DF-170-181103-8891686_0020.15', 'bolt-eng-DF-170-181103-8891686_0020.16', 'web1-eng-DF-241-201379-5514596_0001.1', 'web1-eng-DF-241-201379-5514596_0001.2', 'bolt-eng-DF-170-181103-8886126_0017.1', 'bolt-eng-DF-170-181103-8886126_0017.2', 'bolt-eng-DF-170-181103-8886126_0017.4', 'bolt-eng-DF-170-181103-8886126_0017.5', 'bolt-eng-DF-170-181103-8886126_0017.6', 'bolt-eng-DF-170-181103-8886126_0017.7', 'bolt-eng-DF-170-181103-8886126_0017.8', 'bolt-eng-DF-201-185510-351190_0311.1', 'bolt-eng-DF-201-185510-351190_0311.2', 'bolt-eng-DF-201-185510-351190_0311.3', 'bolt-eng-DF-201-185510-351190_0311.4', 'bolt-eng-DF-201-185510-351190_0311.5', 'bolt-eng-DF-201-185510-351190_0311.6', 'bolt-eng-DF-170-181103-8889674_0059.13', 'bolt-eng-DF-170-181103-8889674_0059.14', 'bolt-eng-DF-170-181103-8889674_0059.15', 'bolt-eng-DF-170-181103-8889674_0059.16', 'bolt-eng-DF-170-181103-8889674_0058.1', 'bolt-eng-DF-170-181103-8889674_0058.2', 'bolt-eng-DF-170-181103-8889674_0058.3', 'bolt-eng-DF-170-181103-8889674_0058.4', 'bolt-eng-DF-170-181103-8889674_0058.5', 'bolt-eng-DF-170-181103-8889674_0058.6', 'bolt-eng-DF-170-181103-8889674_0058.7', 'bolt-eng-DF-170-181105-8850361_0028.15', 'bolt-eng-DF-170-181105-8850361_0028.17', 'bolt-eng-DF-170-181105-8850361_0028.18', 'bolt-eng-DF-170-181105-8850361_0028.19', 'bolt-eng-DF-170-181105-8850361_0028.20', 'bolt-eng-DF-170-181105-8850361_0028.21', 'bolt-eng-DF-170-181105-8850361_0028.22', 'bolt-eng-DF-170-181105-8850361_0028.23', 'bolt-eng-DF-170-181105-8850361_0028.25', 'bolt-eng-DF-170-181105-8850361_0028.26', 'bolt-eng-DF-170-181105-8850361_0028.27', 'bolt-eng-DF-170-181105-8850361_0028.28', 'bolt-eng-DF-170-181105-8850361_0028.29', 'bolt-eng-DF-170-181105-8850361_0028.30', 'bolt-eng-DF-170-181105-8850361_0028.31', 'bolt-eng-DF-170-181105-8850361_0028.32', 'bolt-eng-DF-170-181105-8850361_0028.33', 'bolt-eng-DF-201-185510-351190_0310.1', 'bolt-eng-DF-201-185510-351190_0310.2', 'bolt-eng-DF-201-185510-351190_0310.4', 'bolt-eng-DF-201-185510-351190_0310.5', 'bolt-eng-DF-201-185510-351190_0310.6', 'bolt-eng-DF-201-185510-351190_0310.7', 'bolt-eng-DF-201-185510-351190_0310.8', 'bolt-eng-DF-201-185510-351190_0310.9', 'bolt-eng-DF-201-185510-351190_0310.10', 'bolt-eng-DF-201-185510-351190_0310.11', 'bolt-eng-DF-201-185510-351190_0310.12', 'bolt-eng-DF-201-185510-351190_0310.13', 'bolt-eng-DF-201-185510-351190_0310.14', 'bolt-eng-DF-201-185510-351190_0310.16', 'bolt-eng-DF-201-185510-351190_0310.17', 'bolt-eng-DF-201-185510-351190_0310.33', 'bolt-eng-DF-201-185510-351190_0310.35', 'DF-170-181110-876_5210.10'])

In [219]:
list(train_data['lpp_1943.12'].keys())[0]

'frightened-2'

In [220]:
train_data['lpp_1943.12']['frightened-2']

{'LABEL': 1,
 'ARGM-CAU': [-0.27480408549308777,
  0.714698314666748,
  -4.059543132781982,
  1.2532035112380981,
  -2.112856864929199,
  -1.3800097703933716,
  -1.2238043546676636,
  3.35485577583313,
  -0.48253297805786133,
  0.05253693833947182,
  -0.7601242065429688,
  -0.06180340051651001,
  0.18914654850959778,
  1.029049038887024,
  -0.43090900778770447,
  2.9023690223693848,
  -0.23654034733772278,
  1.2979989051818848,
  -1.5577071905136108,
  1.2718422412872314,
  -0.9503739476203918,
  -3.230721950531006,
  0.6173940896987915,
  1.5127170085906982,
  -0.3876633644104004,
  -0.6552905440330505,
  1.552248477935791,
  -5.221429347991943,
  -1.179642677307129,
  2.906890392303467,
  2.0420074462890625,
  0.4639958441257477,
  -1.3114439249038696,
  -2.7852489948272705,
  2.4857192039489746,
  1.380673885345459,
  2.915138006210327,
  1.283930778503418,
  1.2672699689865112,
  -1.5676358938217163,
  -1.0637099742889404,
  0.7816864848136902,
  1.2741726636886597,
  0.42820972204208374,
  3.9566335678100586,
  0.8976457715034485,
  0.3922257125377655,
  -0.4078632593154907,
  2.4145326614379883,
  -1.7036104202270508,
  0.6882060766220093,
  1.977718472480774,
  1.397809624671936,
  -1.0133169889450073,
  -0.7481048107147217,
  -1.6965701580047607,
  0.6575384140014648,
  -0.7634338140487671,
  -0.32581135630607605,
  0.31040894985198975,
  2.9249448776245117,
  -1.777312994003296,
  -0.6395555138587952,
  0.03280041739344597,
  -1.1621954441070557,
  0.15989373624324799,
  -1.0025132894515991,
  -2.329380750656128,
  -1.8742156028747559,
  0.4910193085670471,
  -1.7193650007247925,
  -0.42313578724861145,
  0.9436277151107788,
  -0.38342633843421936,
  -2.0647754669189453,
  -1.9663647413253784,
  0.6102633476257324,
  1.2618083953857422,
  -1.2764286994934082,
  -0.15039636194705963,
  -5.486393928527832,
  1.129042148590088,
  -1.0920071601867676,
  -0.5941694378852844,
  0.44372668862342834,
  2.601774215698242,
  -0.10900198668241501,
  -0.12561941146850586,
  -2.0839602947235107,
  0.9714542627334595,
  -2.120804786682129,
  0.8750489950180054,
  0.542384147644043,
  -0.629140317440033,
  -0.3923563063144684,
  1.2226941585540771,
  -0.7304056882858276,
  1.2349839210510254,
  0.022089410573244095,
  1.6328785419464111,
  2.9592959880828857,
  -4.2007856369018555,
  -0.2362358570098877,
  -0.34442779421806335,
  1.0893118381500244,
  0.32346540689468384,
  -0.5106751918792725,
  1.6092760562896729,
  -2.6244351863861084,
  0.8819237947463989,
  1.874252438545227,
  -2.8039844036102295,
  -1.9190177917480469,
  0.9352467656135559,
  -1.7664399147033691,
  1.6369017362594604,
  -0.9386277794837952,
  -0.6688017845153809,
  -0.6981649994850159,
  -0.7552498579025269,
  0.6151368618011475,
  -3.3346478939056396,
  -0.4303712844848633,
  -1.013358473777771,
  -2.1591649055480957,
  0.9917755722999573,
  -0.2973513603210449,
  -1.3494879007339478,
  -2.801384687423706,
  -1.2652099132537842,
  0.8810536861419678,
  1.4166151285171509,
  0.6618219614028931,
  -7.6378679275512695,
  -0.9718533754348755,
  1.7561959028244019,
  -0.7285935878753662,
  3.5781099796295166,
  0.3689734935760498,
  0.07529030740261078,
  -1.2980211973190308,
  -0.9428951740264893,
  2.2453596591949463,
  -0.7142202258110046,
  0.38444554805755615,
  -0.8583425283432007,
  0.5888993740081787,
  -0.4614379107952118,
  -1.2163591384887695,
  1.5688225030899048,
  2.283484697341919,
  -1.2041796445846558,
  -0.6878928542137146,
  1.5898237228393555,
  -0.6122999787330627,
  1.9061028957366943,
  -2.543612480163574,
  -0.2879753112792969,
  -0.23752832412719727,
  -0.08907503634691238,
  1.0140529870986938,
  -0.6819058060646057,
  0.08787792921066284,
  -2.24924373626709,
  2.8878374099731445,
  0.6228100657463074,
  -1.5723990201950073,
  -0.14429403841495514,
  0.8695541620254517,
  -0.2694057822227478,
  -2.537480115890503,
  1.2722476720809937,
  2.7753310203552246,
  0.44309186935424805,
  2.5217926502227783,
  1.9808681011199951,
  3.2952370643615723,
  1.2404931783676147,
  0.44978392124176025,
  0.5385643243789673,
  2.859881639480591,
  -1.3001710176467896,
  -0.24974003434181213,
  -4.557772159576416,
  19.815235137939453,
  0.7017218470573425,
  -2.4368555545806885,
  -0.9186910390853882,
  0.5220355987548828,
  0.587164044380188,
  0.17929518222808838,
  -0.5196769833564758,
  -2.5893332958221436,
  0.8581842184066772,
  -1.1987313032150269,
  -0.6795840859413147,
  -1.4574048519134521,
  -0.6284409761428833,
  -2.531049966812134,
  2.0362954139709473,
  1.946724534034729,
  2.6385793685913086,
  -0.7154812216758728,
  1.1509958505630493,
  -0.9367712736129761,
  -0.6400362253189087,
  -0.9779939651489258,
  0.39854946732521057,
  1.3936532735824585,
  3.085249185562134,
  1.226811408996582,
  3.3764450550079346,
  -0.8946683406829834,
  1.1922855377197266,
  -2.2381060123443604,
  -3.205811023712158,
  0.09303464740514755,
  -4.116777420043945,
  1.0732725858688354,
  0.28304973244667053,
  -1.4216787815093994,
  -1.4846268892288208,
  0.27462896704673767,
  -0.5477489233016968,
  -2.7511796951293945,
  -2.740729808807373,
  0.8022204041481018,
  -2.2202324867248535,
  3.0631980895996094,
  3.600545644760132,
  -2.5018179416656494,
  -0.295536607503891,
  -1.487342119216919,
  -1.0425840616226196,
  -0.6978897452354431,
  -3.179365634918213,
  -5.735208511352539,
  1.266861081123352,
  1.7425613403320312,
  0.4148128926753998,
  1.018457293510437,
  1.4716347455978394,
  3.911125421524048,
  4.928009033203125,
  2.5363943576812744,
  0.6637214422225952,
  -2.2795276641845703,
  1.3224992752075195,
  1.919685959815979,
  0.3209144175052643,
  -0.7105432152748108,
  -1.006698489189148,
  -0.6072665452957153,
  3.696166753768921,
  -1.0536352396011353,
  3.1554291248321533,
  0.5968800783157349,
  0.2651621997356415,
  0.3155610263347626,
  -0.7163234353065491,
  2.7354650497436523,
  -0.6847797632217407,
  1.2336777448654175,
  -0.14727406203746796,
  -1.1843459606170654,
  -3.4422664642333984,
  -0.8931748867034912,
  -2.0466208457946777,
  3.505344867706299,
  0.6272394061088562,
  0.5714995861053467,
  -2.121009588241577,
  -0.272312194108963,
  -1.4646003246307373,
  -1.1651970148086548,
  -1.470866322517395,
  0.9492735266685486,
  -2.3354806900024414,
  1.6378498077392578,
  -1.078452229499817,
  -2.8865432739257812,
  -1.0275530815124512,
  4.258150100708008,
  2.049327850341797,
  1.3258918523788452,
  -1.4410243034362793,
  1.2750248908996582,
  1.9781455993652344,
  -1.9133381843566895,
  5.6993513107299805,
  3.387239933013916,
  1.67840576171875,
  -8.367298126220703,
  -5.874081611633301,
  -4.3442535400390625,
  -0.3460523188114166,
  0.9530975222587585,
  -1.1659077405929565,
  -0.4753563702106476,
  2.937481641769409,
  -0.7490142583847046,
  -0.8264985680580139,
  -3.1145148277282715,
  0.3147881031036377,
  -1.313740849494934,
  1.9627137184143066,
  -2.827789545059204,
  0.40928545594215393,
  0.0937882512807846,
  -1.0777084827423096,
  0.49253493547439575,
  2.6782588958740234,
  -0.9470644593238831,
  1.2486827373504639,
  -1.0433446168899536,
  1.888104796409607,
  0.4838172495365143,
  3.2024459838867188,
  0.1276022046804428,
  0.22043415904045105,
  9.247732162475586,
  -2.4061243534088135,
  -2.239468812942505,
  0.13915033638477325,
  3.1283183097839355,
  0.9988567233085632,
  0.20199447870254517,
  1.1616370677947998,
  -0.2991993725299835,
  0.006442304700613022,
  -3.1625497341156006,
  1.843760371208191,
  0.15173839032649994,
  3.336500883102417,
  0.10989736765623093,
  0.3207264542579651,
  0.05808113142848015,
  -0.24017436802387238,
  1.4381192922592163,
  -0.6290143132209778,
  0.9597848057746887,
  -0.20875246822834015,
  2.414391040802002,
  0.3406839966773987,
  2.571436643600464,
  2.3113632202148438,
  1.2635663747787476,
  -0.7058139443397522,
  -0.7239899635314941,
  4.972445487976074,
  1.5085586309432983,
  -1.8623006343841553,
  2.818647861480713,
  -0.17195867002010345,
  1.3311045169830322,
  3.0427491664886475,
  0.5447437763214111,
  0.11772830784320831,
  0.6939647793769836,
  3.4034454822540283,
  -0.8917972445487976,
  1.372106671333313,
  1.5386908054351807,
  1.1113777160644531,
  -1.6400794982910156,
  -3.8480350971221924,
  -3.4490036964416504,
  -0.33055970072746277,
  0.9150548577308655,
  -0.9029871225357056,
  1.0891139507293701,
  -1.9549639225006104,
  -2.1841254234313965,
  2.850114583969116,
  1.5725144147872925,
  1.6248890161514282,
  -1.1993035078048706,
  0.5425627827644348,
  1.621960163116455,
  0.24010810256004333,
  -2.3430206775665283,
  -1.65537428855896,
  -0.21693941950798035,
  -0.285580039024353,
  4.180193901062012,
  -1.839896321296692,
  -1.2876110076904297,
  -5.678416728973389,
  -3.5030171871185303,
  -0.4185640513896942,
  0.18514259159564972,
  -0.936411440372467,
  -2.980395793914795,
  0.6138514876365662,
  -1.0602726936340332,
  -1.2665671110153198,
  -0.03990346938371658,
  4.492704391479492,
  -1.9635924100875854,
  0.9809767603874207,
  0.6625669002532959,
  -3.152301788330078,
  0.9057029485702515,
  0.35167166590690613,
  -2.1615984439849854,
  -1.2098941802978516,
  11.296927452087402,
  -2.5833160877227783,
  2.304187297821045,
  -0.5625783205032349,
  1.0476436614990234,
  -0.18123555183410645,
  0.518042802810669,
  0.13736553490161896,
  -0.5371241569519043,
  1.4705195426940918,
  1.8284738063812256,
  1.1191701889038086,
  -0.1278763860464096,
  -0.5679819583892822,
  2.805321216583252,
  -0.5853899717330933,
  0.4358751177787781,
  0.5938522219657898,
  1.19789719581604,
  1.8995541334152222,
  -0.6747822761535645,
  0.2160148173570633,
  -2.702026128768921,
  -0.8526703119277954,
  -0.6770297288894653,
  -2.6588780879974365,
  -3.377046585083008,
  1.8050615787506104,
  -1.9572818279266357,
  -3.853853464126587,
  1.2682219743728638,
  -0.9484652876853943,
  -2.213369131088257,
  -0.30120569467544556,
  -0.0017594225937500596,
  -0.15001288056373596,
  0.2636980712413788,
  0.16898378729820251,
  -2.6970202922821045,
  1.5494518280029297,
  0.8750674724578857,
  0.9089947938919067,
  -0.05428041145205498,
  0.7985725998878479,
  -0.47696900367736816,
  1.8973286151885986,
  -0.9487910270690918,
  -1.3639531135559082,
  2.327995777130127,
  -3.5518507957458496,
  1.758400797843933,
  -4.638742923736572,
  -0.09150200337171555,
  2.1925852298736572,
  -2.088258981704712,
  -2.1842899322509766,
  0.46113643050193787,
  -1.0345840454101562,
  -0.304478257894516,
  1.5786912441253662,
  2.4397783279418945,
  0.6452187895774841,
  -0.21243879199028015,
  0.8402087688446045,
  0.9452163577079773,
  -2.2704925537109375,
  -0.1240222156047821,
  0.923691987991333,
  0.8427539467811584,
  0.41069644689559937,
  1.7618963718414307,
  0.0749322846531868,
  -1.790164589881897,
  -0.837775468826294,
  -2.355271577835083,
  -0.310721755027771,
  -1.2977242469787598,
  0.35060954093933105,
  0.18606655299663544,
  0.7937211394309998,
  -1.045441746711731,
  2.2532689571380615,
  -0.7178946137428284,
  1.8428752422332764,
  -1.4814324378967285,
  2.7011828422546387,
  1.717814564704895,
  2.1041176319122314,
  1.1441398859024048,
  0.33537957072257996,
  -1.3180433511734009,
  -3.78434419631958,
  -0.23177501559257507,
  -0.5517368316650391,
  0.005769323091953993,
  -0.30522796511650085,
  -2.9661903381347656,
  2.7953977584838867,
  6.6934990882873535,
  1.1226321458816528,
  -1.9846299886703491,
  1.0668727159500122,
  -3.723581075668335,
  -1.5540343523025513,
  3.9404258728027344,
  -1.8769450187683105,
  2.7412643432617188,
  2.5732944011688232,
  -0.4645370543003082,
  0.0252325851470232,
  0.6937333345413208,
  0.054764214903116226,
  8.571534156799316,
  0.7842950820922852,
  1.1177527904510498,
  2.246213674545288,
  2.7499570846557617,
  -1.7533583641052246,
  -0.13097642362117767,
  -1.5283443927764893,
  -0.40353018045425415,
  -1.4695762395858765,
  -0.5837364792823792,
  1.3704301118850708,
  -0.4785105288028717,
  0.7862293720245361,
  1.9847875833511353,
  0.2908079922199249,
  -2.4768474102020264,
  0.2056305706501007,
  -1.0856190919876099,
  -3.0995123386383057,
  1.3147729635238647,
  -0.6847460865974426,
  1.3984977006912231,
  -0.49827805161476135,
  1.234216332435608,
  -3.3865394592285156,
  1.3972371816635132,
  2.738903522491455,
  0.18988797068595886,
  -1.5655630826950073,
  -0.2049587517976761,
  -0.4133659303188324,
  0.08097787201404572,
  -4.27148962020874,
  -0.5069423317909241,
  0.4464307725429535,
  3.40541410446167,
  0.6535347700119019,
  0.45604178309440613,
  -0.0434226468205452,
  -2.063372850418091,
  0.4562237560749054,
  0.37281274795532227,
  -0.25439581274986267,
  0.5865747928619385,
  4.089028835296631,
  -0.051938172429800034,
  -1.0212090015411377,
  -4.019395351409912,
  -1.4895524978637695,
  0.22631332278251648,
  1.0100464820861816,
  -2.1255810260772705,
  2.194399118423462,
  -1.3929286003112793,
  -0.8543236255645752,
  0.9942687153816223,
  -1.7951408624649048,
  4.179544925689697,
  -0.4778536558151245,
  3.178419589996338,
  0.5197647213935852,
  -0.13175909221172333,
  -1.1882877349853516,
  1.2598934173583984,
  -1.2362070083618164,
  1.2079107761383057,
  1.4037643671035767,
  0.5392906069755554,
  -0.17220446467399597,
  -1.2764021158218384,
  2.964949369430542,
  0.4334886074066162,
  0.738103985786438,
  -0.8329598903656006,
  -2.525308609008789,
  1.5873899459838867,
  0.9684008955955505,
  0.8788133859634399,
  -3.5426721572875977,
  2.4953505992889404,
  1.0366677045822144,
  0.8368746042251587,
  0.3222980797290802,
  1.4303795099258423,
  -0.45199593901634216,
  -1.8275740146636963,
  0.4826483130455017,
  -0.9406582713127136,
  0.3684968948364258,
  -2.17740535736084,
  -0.16020432114601135,
  -4.868113994598389,
  -6.636192798614502,
  0.10879352688789368,
  0.7996327877044678,
  -2.2346866130828857,
  -2.6879663467407227,
  -1.6936622858047485,
  0.26177531480789185,
  -1.453270673751831,
  0.21854263544082642,
  2.0330750942230225,
  1.3701870441436768,
  2.2851107120513916,
  -1.203291654586792,
  -3.5981404781341553,
  -2.813033103942871,
  -1.1626842021942139,
  -0.6595225930213928,
  -0.6436315178871155,
  -1.0362606048583984,
  0.4192149043083191,
  -4.227247714996338,
  -0.5040766000747681,
  0.7815327048301697,
  -0.24461030960083008,
  0.08925744146108627,
  -2.1453845500946045,
  -0.41412460803985596,
  -0.6621700525283813,
  -2.132265329360962,
  -0.2071610391139984,
  14.228044509887695,
  -4.629385948181152,
  2.037207841873169,
  -0.37358158826828003,
  3.4985203742980957,
  4.079298973083496,
  0.6311918497085571,
  -1.8567569255828857,
  1.6415446996688843,
  -1.2195967435836792,
  1.400513768196106,
  -0.0961155816912651,
  1.7849810123443604,
  1.7332448959350586,
  1.4498028755187988,
  1.2153911590576172,
  -2.438227891921997,
  2.9158453941345215,
  -0.09249468892812729,
  -1.1133801937103271,
  -0.6267893314361572,
  0.2152661234140396,
  -2.0818493366241455,
  -1.2111709117889404,
  1.9657338857650757,
  -0.07154787331819534,
  -2.034135580062866,
  -1.7483549118041992,
  -1.9639060497283936,
  3.7330820560455322,
  2.0083324909210205,
  0.1819925755262375,
  -1.141797661781311,
  -2.1773104667663574,
  -1.3118455410003662,
  3.8037049770355225,
  -0.3941402733325958,
  0.8127487897872925,
  0.7230522632598877,
  1.7510550022125244,
  1.158233880996704,
  -0.033888425678014755,
  -1.4941132068634033,
  0.10327517986297607,
  -1.6756808757781982,
  2.506687879562378,
  3.4714739322662354,
  -1.287414789199829,
  1.7418432235717773,
  1.4391324520111084,
  -0.5122014880180359,
  -0.3525784909725189,
  3.0640456676483154,
  -0.4123992323875427,
  -0.9265596270561218,
  -0.17007534205913544,
  -1.1656155586242676,
  0.2015870213508606,
  0.7867968082427979,
  -0.1885146200656891,
  -3.2263519763946533,
  1.901569128036499,
  1.171291470527649,
  -1.7692210674285889,
  -0.18858785927295685,
  0.9480089545249939,
  -0.19604434072971344,
  -2.2737600803375244,
  -3.9396517276763916,
  -0.7060889601707458,
  -0.15708141028881073,
  3.4898829460144043,
  3.568417549133301,
  -1.032702088356018,
  2.74084210395813,
  2.072628974914551,
  -0.11887725442647934,
  0.6849455237388611,
  -1.9424464702606201,
  1.7368013858795166,
  1.092820405960083,
  2.0122010707855225,
  1.0563908815383911,
  1.5786242485046387,
  0.26933202147483826,
  3.4280967712402344,
  -1.3838393688201904,
  -0.6171784400939941,
  -1.068922758102417,
  0.6922043561935425,
  -0.6968770623207092,
  -1.4962670803070068,
  -1.6353398561477661,
  1.1405366659164429,
  0.7389647960662842,
  2.305685043334961,
  4.0954365730285645,
  0.14920678734779358,
  -1.188002586364746,
  0.4746797978878021,
  0.7443030476570129,
  -2.5947930812835693,
  -0.31244638562202454,
  -0.14954447746276855,
  -1.3138058185577393,
  0.29759421944618225,
  3.0172879695892334,
  0.7364268898963928,
  0.9971946477890015,
  0.08321654051542282,
  1.4859591722488403,
  -1.1755311489105225,
  -0.31154465675354004,
  -2.8726346492767334,
  -0.388579785823822,
  -2.7622156143188477,
  -0.11224304139614105,
  3.712012767791748,
  -0.8223603367805481,
  -2.3204104900360107,
  3.553694009780884,
  -0.7918153405189514,
  0.34457144141197205,
  -1.6627696752548218,
  2.6384830474853516,
  0.11375772207975388,
  1.5851961374282837,
  0.5977694988250732,
  0.5835884809494019,
  1.367234706878662,
  1.5355629920959473,
  -1.147557020187378,
  -2.118955135345459,
  2.597752571105957,
  -0.007255816366523504,
  -0.2224123179912567,
  -0.06741031259298325,
  -1.3514961004257202,
  -0.4941631257534027,
  -0.8429163098335266,
  -1.1054273843765259,
  20.43865966796875,
  -0.4663153290748596,
  1.389047622680664,
  -0.3511364758014679,
  -1.3256982564926147,
  3.0020391941070557,
  1.273021936416626,
  3.72182559967041,
  -0.019888272508978844,
  -0.19020627439022064,
  0.0770418643951416,
  -3.116150140762329,
  1.7072701454162598,
  1.976420283317566,
  -1.0358625650405884,
  -2.1335513591766357,
  -1.3327443599700928,
  -2.5103838443756104,
  -2.0504415035247803,
  -1.5542346239089966,
  -3.4787795543670654,
  -3.394965887069702,
  -1.7749848365783691,
  0.9217070937156677,
  0.540107250213623,
  0.8143264055252075,
  -1.3482921123504639,
  2.4946556091308594,
  -2.0114595890045166,
  -0.9063048958778381,
  2.9067344665527344,
  -0.4512343108654022,
  1.511448860168457,
  -0.9942364692687988,
  0.2038291096687317,
  -0.7887070178985596,
  2.3716750144958496,
  -1.0177901983261108,
  -0.818496584892273,
  -3.675111770629883,
  2.2642579078674316,
  -1.2963829040527344,
  0.4218001961708069,
  -0.17071907222270966,
  -1.1924927234649658,
  2.3261163234710693,
  0.48910704255104065,
  -1.8580710887908936,
  0.08792244642972946,
  -1.543304681777954,
  2.359863519668579,
  -0.8463187217712402,
  1.2293378114700317,
  2.310389995574951,
  -1.5096250772476196,
  0.9070609211921692,
  -0.750148594379425,
  1.0663821697235107,
  -0.09065882116556168,
  0.8537731766700745,
  0.4302712678909302,
  -0.4132606089115143,
  0.33840593695640564,
  0.018385225906968117,
  0.17290298640727997,
  -5.004675388336182,
  1.641074538230896,
  0.28942710161209106,
  0.6486342549324036,
  -1.3824511766433716,
  0.5324597358703613,
  0.2799715995788574,
  -0.88509202003479,
  0.23348043859004974,
  -0.38804954290390015,
  -0.2560275197029114,
  1.9106040000915527,
  2.0697689056396484,
  1.2239701747894287,
  1.6953985691070557,
  -1.114680528640747,
  0.6362297534942627,
  -0.3615305721759796,
  -2.2888526916503906,
  -0.031126897782087326,
  2.2728748321533203,
  2.7126452922821045,
  -0.8878664970397949,
  2.5300114154815674,
  2.076439142227173,
  -0.6934155225753784,
  -2.73496150970459,
  0.25711822509765625,
  2.425100564956665,
  2.0721089839935303,
  0.7420285940170288,
  -0.012139523401856422,
  -1.240673303604126,
  -0.32946348190307617,
  0.3728469908237457,
  1.867383599281311,
  3.220954418182373,
  0.517264723777771,
  2.4604148864746094,
  2.488877773284912,
  -0.22937403619289398,
  0.22043439745903015,
  7.160943508148193,

In [215]:
for d in train_data:
    print(d)
    break

lpp_1943.12

In [214]:
len(train_data)

373

In [213]:
train_data['bolt-eng-DF-201-185510-351190_0310.18']

KeyError: 'bolt-eng-DF-201-185510-351190_0310.18'

In [4]:
data_list[0]

{'lpp_1943.1': [[-3.1708171367645264,
   -2.398267984390259,
   2.241295337677002,
   0.9565747976303101,
   0.49656420946121216,
   3.2837002277374268,
   -0.44181784987449646,
   -1.0049179792404175,
   0.9659172892570496,
   -1.6169227361679077,
   -0.7834728360176086,
   -1.9014338254928589,
   -3.214379072189331,
   -1.349833607673645,
   1.7135506868362427,
   -0.23368406295776367,
   -1.1997109651565552,
   1.1412022113800049,
   0.3187262713909149,
   0.04427489638328552,
   1.1475270986557007,
   4.046060085296631,
   1.2865207195281982,
   1.630428433418274,
   0.2861955463886261,
   -1.0528091192245483,
   0.30863770842552185,
   0.11568811535835266,
   -0.2441854178905487,
   2.0849761962890625,
   1.3683371543884277,
   -0.32840660214424133,
   2.7802603244781494,
   1.844836950302124,
   0.36883339285850525,
   3.745657205581665,
   -2.7124950885772705,
   -0.9763656854629517,
   -0.9286210536956787,
   -1.6004927158355713,
   -1.9224714040756226,
   -2.663257360458374,
   -1.4220240116119385,
   1.3151767253875732,
   0.06810586154460907,
   -0.2885327935218811,
   -0.08624152839183807,
   0.21511907875537872,
   -0.9242472052574158,
   2.267366647720337,
   -1.629923939704895,
   -0.8617451190948486,
   0.15390799939632416,
   -0.11089006066322327,
   -1.7689570188522339,
   1.5690288543701172,
   -1.3265053033828735,
   -1.0670418739318848,
   -3.8878681659698486,
   0.07339310646057129,
   -0.8529883027076721,
   -1.2007973194122314,
   -1.3509495258331299,
   6.046727180480957,
   0.9837833642959595,
   -1.79293954372406,
   -2.5829660892486572,
   -1.44021737575531,
   -0.5870935916900635,
   1.4959102869033813,
   0.9891809821128845,
   -2.832821846008301,
   -0.6992523074150085,
   -2.088083028793335,
   1.7485872507095337,
   -1.5742523670196533,
   -1.5087271928787231,
   1.5974764823913574,
   -0.9820451736450195,
   -2.164393186569214,
   1.601352334022522,
   1.4939693212509155,
   -1.8518388271331787,
   3.0052249431610107,
   0.20880724489688873,
   -1.30354642868042,
   1.3383516073226929,
   -2.5397167205810547,
   0.3234238028526306,
   -1.6594847440719604,
   1.1352460384368896,
   -2.436652660369873,
   -1.042370319366455,
   2.3619799613952637,
   -1.344080924987793,
   1.9754672050476074,
   0.2755114734172821,
   -1.4841816425323486,
   1.9928412437438965,
   -1.4125896692276,
   0.3654171824455261,
   -3.5964653491973877,
   -1.7872343063354492,
   0.3541863262653351,
   0.0905161127448082,
   0.32153767347335815,
   -0.057211436331272125,
   1.676468014717102,
   -2.4182803630828857,
   2.6463637351989746,
   0.6509127020835876,
   -1.0214508771896362,
   1.0385890007019043,
   0.9174546003341675,
   -0.12239380925893784,
   -2.5302183628082275,
   1.7407488822937012,
   1.521510362625122,
   -1.9346786737442017,
   2.8746848106384277,
   0.13122005760669708,
   1.067094326019287,
   -3.675781011581421,
   -3.8127307891845703,
   2.4409737586975098,
   -1.4476054906845093,
   0.7921099066734314,
   1.3290050029754639,
   -0.4852961301803589,
   0.682659924030304,
   -1.6117507219314575,
   0.9365295767784119,
   3.884016990661621,
   4.388093948364258,
   -0.18987347185611725,
   0.10992620885372162,
   -0.7004426717758179,
   0.7742122411727905,
   0.1469615250825882,
   -1.6972777843475342,
   0.7651131749153137,
   -0.758627712726593,
   -1.6625573635101318,
   2.6715517044067383,
   -0.5421690940856934,
   0.48886406421661377,
   -2.4172146320343018,
   1.5718270540237427,
   0.3521636724472046,
   3.3956282138824463,
   2.559309959411621,
   1.1327136754989624,
   -2.2631354331970215,
   -1.2531005144119263,
   -0.24786831438541412,
   -0.6545195579528809,
   0.24212637543678284,
   2.4902751445770264,
   -0.5494697690010071,
   -2.2894933223724365,
   0.0907701626420021,
   2.488083600997925,
   0.7854316234588623,
   2.3988513946533203,
   1.211606502532959,
   1.546645998954773,
   3.3740880489349365,
   -1.3346095085144043,
   -1.3649849891662598,
   0.7877892851829529,
   -0.6340687274932861,
   0.3882625997066498,
   -2.4164819717407227,
   0.365113765001297,
   1.8923348188400269,
   -2.9086549282073975,
   -4.109299659729004,
   -0.40654075145721436,
   0.46361175179481506,
   0.10457047820091248,
   1.9395227432250977,
   1.0603147745132446,
   4.266690731048584,
   -0.37312304973602295,
   17.497257232666016,
   -1.0640469789505005,
   -3.0874037742614746,
   -0.09724493324756622,
   2.549285888671875,
   2.595776081085205,
   -1.492903470993042,
   -0.9652116894721985,
   1.0412145853042603,
   -2.137471914291382,
   1.784680724143982,
   1.2269494533538818,
   0.5391848683357239,
   3.178607225418091,
   0.7805718779563904,
   2.6272778511047363,
   1.3726216554641724,
   -0.09636931866407394,
   -0.09031916409730911,
   -1.0309748649597168,
   1.236340045928955,
   0.15599572658538818,
   1.8585222959518433,
   -0.912400484085083,
   3.672497034072876,
   -0.6462486386299133,
   -1.1685338020324707,
   -2.273266553878784,
   -1.1782840490341187,
   -0.596992015838623,
   0.009044433943927288,
   1.8806159496307373,
   -0.2770346999168396,
   -1.5907833576202393,
   -1.0348999500274658,
   -0.9159628748893738,
   0.3821619749069214,
   -0.1463298797607422,
   -2.2573065757751465,
   -2.4668774604797363,
   3.06990385055542,
   -0.009494704194366932,
   0.002295732730999589,
   4.0961995124816895,
   -0.28982529044151306,
   -2.0302608013153076,
   -3.040607452392578,
   -1.049459457397461,
   -0.03090924397110939,
   -2.292853832244873,
   0.14659720659255981,
   0.7126369476318359,
   2.0702669620513916,
   0.20398737490177155,
   -2.5545921325683594,
   -0.6142014861106873,
   1.8191945552825928,
   1.143925428390503,
   0.09929642826318741,
   1.258695125579834,
   0.04137185588479042,
   -0.5780683159828186,
   -1.3486769199371338,
   -2.570981025695801,
   -1.4457114934921265,
   -2.3593697547912598,
   0.03624832630157471,
   0.5058501362800598,
   0.9454167485237122,
   -3.372981548309326,
   -0.47716668248176575,
   -0.5046131610870361,
   -3.4948673248291016,
   1.7631311416625977,
   -1.6202479600906372,
   2.4399466514587402,
   2.4380176067352295,
   -2.343189001083374,
   -0.630639910697937,
   -0.7042477130889893,
   -1.1659921407699585,
   -3.3043341636657715,
   0.7297565340995789,
   2.6176095008850098,
   -1.081011176109314,
   -0.7000222206115723,
   -1.039130687713623,
   -3.7562780380249023,
   0.3084027171134949,
   -2.5340607166290283,
   -1.7327390909194946,
   -2.1441726684570312,
   -4.255865573883057,
   -4.9716339111328125,
   -2.5645434856414795,
   -0.9302662014961243,
   -2.290915012359619,
   -5.667466640472412,
   -3.1271119117736816,
   -1.8560850620269775,
   -2.111018419265747,
   -1.1888962984085083,
   -1.2255507707595825,
   -1.1252106428146362,
   1.0908448696136475,
   -13.758241653442383,
   4.77687406539917,
   -0.7735487818717957,
   5.478048801422119,
   0.16440273821353912,
   -1.539038896560669,
   0.35646045207977295,
   1.6412596702575684,
   -0.24340014159679413,
   1.758693814277649,
   -0.8235981464385986,
   1.050589919090271,
   -1.313352346420288,
   0.2879549264907837,
   -1.2480053901672363,
   1.4871488809585571,
   -1.3760994672775269,
   -1.0054579973220825,
   -3.6707520484924316,
   0.4106489419937134,
   0.5383305549621582,
   -1.8282172679901123,
   5.250373840332031,
   0.19758954644203186,
   -4.4690961837768555,
   1.2735509872436523,
   3.35697865486145,
   0.307993084192276,
   -0.395911306142807,
   -0.1416507065296173,
   0.6828221082687378,
   12.980313301086426,
   0.6215248107910156,
   0.5668180584907532,
   0.651255190372467,
   -0.9049018621444702,
   -0.5615177154541016,
   -2.8557732105255127,
   -0.12229441851377487,
   3.976994752883911,
   0.6579626202583313,
   -0.5050708651542664,
   0.31388580799102783,
   1.5050548315048218,
   0.3289788067340851,
   -2.4482250213623047,
   0.12533068656921387,
   -0.05485757440328598,
   0.5515801906585693,
   0.9173925518989563,
   0.006315173581242561,
   -0.676387369632721,
   2.096412181854248,
   -1.475699543952942,
   1.2267721891403198,
   0.34785112738609314,
   -1.2104942798614502,
   -0.053762808442115784,
   -1.972115397453308,
   -0.9819071292877197,
   2.94284725189209,
   -1.958467960357666,
   -3.5618135929107666,
   1.3873481750488281,
   0.6913621425628662,
   -0.5405832529067993,
   -0.6632736921310425,
   -0.05654270574450493,
   -1.1446483135223389,
   1.1472476720809937,
   -0.7771894335746765,
   0.8110249638557434,
   0.8477900624275208,
   -0.06229780241847038,
   -0.028119824826717377,
   -1.488355040550232,
   0.3926149308681488,
   1.103113055229187,
   0.8023620843887329,
   0.4228067398071289,
   1.5693546533584595,
   1.030661940574646,
   -2.5738565921783447,
   -1.9101437330245972,
   2.117805242538452,
   -3.660749912261963,
   -1.9690783023834229,
   4.097473621368408,
   0.3313343822956085,
   -1.332885503768921,
   -1.473279356956482,
   -1.7576178312301636,
   0.9000035524368286,
   -1.2347979545593262,
   4.490455150604248,
   0.40109071135520935,
   -1.9608612060546875,
   1.8192830085754395,
   -0.20813985168933868,
   -0.3765808641910553,
   0.3344295918941498,
   -0.9071030020713806,
   -0.6054764986038208,
   3.237340211868286,
   -2.2402257919311523,
   -0.4011135399341583,
   1.860427737236023,
   -2.025550603866577,
   4.029691219329834,
   0.4264150857925415,
   0.4665590226650238,
   4.052671432495117,
   0.03363636136054993,
   -4.736404895782471,
   -2.1919455528259277,
   -0.5642383098602295,
   1.2055922746658325,
   2.5196754932403564,
   1.0943386554718018,
   -1.6402153968811035,
   -1.3364440202713013,
   -0.32062116265296936,
   0.01782415807247162,
   1.859021544456482,
   -1.285380482673645,
   -1.4809988737106323,
   -1.3104424476623535,
   2.5276451110839844,
   -3.9954710006713867,
   -1.317396879196167,
   1.7284772396087646,
   -0.7318964004516602,
   -1.6921148300170898,
   3.3986668586730957,
   -1.942992925643921,
   -1.0217987298965454,
   1.880293369293213,
   0.968342125415802,
   -0.4104541838169098,
   -2.8043267726898193,
   0.34928804636001587,
   1.159753680229187,
   -0.7095211744308472,
   3.1430344581604004,
   -2.5883092880249023,
   2.288400888442993,
   1.8173282146453857,
   -1.1641288995742798,
   2.721595525741577,
   0.23666150867938995,
   -0.0940675139427185,
   1.194492220878601,
   1.7363207340240479,
   -2.406904458999634,
   1.434686541557312,
   -1.8823953866958618,
   -0.5161601305007935,
   1.132912039756775,
   -2.0705976486206055,
   1.1068577766418457,
   -0.5043964385986328,
   1.8381381034851074,
   -0.12243881821632385,
   0.40159669518470764,
   2.993333339691162,
   -0.9643862247467041,
   -0.9965819120407104,
   -1.291048288345337,
   3.0589513778686523,
   -2.0236523151397705,
   -3.7643401622772217,
   -2.031695604324341,
   -1.4553316831588745,
   0.10542435944080353,
   2.352268934249878,
   3.118562936782837,
   0.6181374788284302,
   -0.8085749745368958,
   4.6153082847595215,
   0.6125132441520691,
   -2.7517905235290527,
   1.4387686252593994,
   -1.6490633487701416,
   4.463872909545898,
   -1.5594147443771362,
   -1.5698732137680054,
   2.4164373874664307,
   -0.2644355297088623,
   2.7192349433898926,
   -0.0021620055194944143,
   -2.2057278156280518,
   1.0877177715301514,
   -0.9615527987480164,
   2.116793632507324,
   -2.409050226211548,
   1.7547953128814697,
   0.3618023991584778,
   -0.5083826184272766,
   1.2865548133850098,
   1.059813380241394,
   0.9370105266571045,
   0.8255548477172852,
   2.8420352935791016,
   -0.06008788198232651,
   0.8994040489196777,
   0.14816798269748688,
   -1.8625997304916382,
   0.5590961575508118,
   1.4210878610610962,
   -2.0526061058044434,
   -0.25541260838508606,
   -0.9136195182800293,
   -0.8851492404937744,
   4.438081741333008,
   -0.884330689907074,
   3.6998836994171143,
   0.25405821204185486,
   -0.9280347228050232,
   -0.46246054768562317,
   1.1434760093688965,
   2.6063458919525146,
   1.0530214309692383,
   0.9788240790367126,
   -2.530190944671631,
   1.1004852056503296,
   -0.597961962223053,
   1.240630030632019,
   0.1591678261756897,
   -1.965804100036621,
   5.312837600708008,
   -2.6427559852600098,
   0.3440605103969574,
   0.9850500226020813,
   -1.6389856338500977,
   -1.3129891157150269,
   -4.681815147399902,
   0.3409615755081177,
   0.8318487405776978,
   2.1331968307495117,
   -2.175421714782715,
   2.677579402923584,
   -1.3182960748672485,
   1.0108375549316406,
   0.5286279916763306,
   0.6645982265472412,
   0.23661521077156067,
   2.5110411643981934,
   -1.4631620645523071,
   0.3518628776073456,
   -6.80955171585083,
   2.5736920833587646,
   0.23203271627426147,
   1.5225452184677124,
   -1.0413154363632202,
   0.5307739973068237,
   -0.7377914786338806,
   -0.2692490518093109,
   -0.10492131114006042,
   2.952502727508545,
   -1.178175926208496,
   -2.887810707092285,
   -2.1119792461395264,
   -1.4474782943725586,
   1.8801155090332031,
   -1.1915676593780518,
   0.7500600218772888,
   -2.9937775135040283,
   0.8543974757194519,
   1.597673773765564,
   -2.4156064987182617,
   2.9447004795074463,
   -1.9550676345825195,
   0.9944165349006653,
   -0.5601791143417358,
   -3.7462315559387207,
   1.0488059520721436,
   -1.12798273563385,
   3.336993932723999,
   2.772463083267212,
   0.4256293475627899,
   -0.5854460000991821,
   1.6422693729400635,
   2.000231981277466,
   -0.926345705986023,
   -2.0695266723632812,
   -0.9177725315093994,
   -2.1886637210845947,
   -1.1626074314117432,
   4.301642417907715,
   -0.5118492841720581,
   1.0301456451416016,
   1.1134727001190186,
   4.038065433502197,
   -0.5207303762435913,
   1.0471395254135132,
   1.4885824918746948,
   -1.6093531847000122,
   1.3522344827651978,
   0.06698960065841675,
   1.075925350189209,
   -1.2764434814453125,
   -3.0633304119110107,
   0.31313201785087585,
   0.7444061040878296,
   2.030215263366699,
   -2.0191211700439453,
   2.1270341873168945,
   1.15693199634552,
   0.7947949171066284,
   0.16902904212474823,
   -0.058684274554252625,
   -1.1915786266326904,
   0.9597325921058655,
   -0.14693187177181244,
   -0.755831241607666,
   2.463501214981079,
   -1.9983946084976196,
   2.5941553115844727,
   -0.3402593731880188,
   -1.0510163307189941,
   -0.6499825716018677,
   -5.65747594833374,
   1.4943023920059204,
   0.04081779345870018,
   1.6614302396774292,
   0.6479913592338562,
   3.6912271976470947,
   4.156617164611816,
   0.7460707426071167,
   -2.512634038925171,
   -3.1758480072021484,
   -0.7888906598091125,
   -1.6973228454589844,
   0.35587120056152344,
   2.1648762226104736,
   4.244095802307129,
   -3.076425552368164,
   4.780924320220947,
   1.0598257780075073,
   -3.5505330562591553,
   0.18000097572803497,
   -3.053910970687866,
   1.8291980028152466,
   0.18417325615882874,
   -0.49819740653038025,
   -2.034536838531494,
   2.527021884918213,
   2.6542441844940186,
   3.214322566986084,
   3.475369453430176,
   -2.9266695976257324,
   1.9841971397399902,
   5.227514743804932,
   0.046583324670791626,
   0.04607995226979256,
   2.591644525527954,
   -0.32296043634414673,
   -4.348992824554443,
   -1.0994887351989746,
   -1.0626015663146973,
   2.539060592651367,
   -2.619166851043701,
   -0.11748813837766647,
   0.9496419429779053,
   -0.4090088903903961,
   -1.5818748474121094,
   0.1714923232793808,
   2.1619186401367188,
   -1.584083080291748,
   1.8786170482635498,
   0.5490656495094299,
   1.3037934303283691,
   -0.37789005041122437,
   -0.31306925415992737,
   1.7243927717208862,
   -0.1387542486190796,
   0.5670151114463806,
   -0.20994704961776733,
   0.579193115234375,
   -3.1885805130004883,
   -0.6320993900299072,
   1.4131852388381958,
   -1.6561981439590454,
   -1.7864950895309448,
   4.977688312530518,
   -1.0059207677841187,
   3.2717411518096924,
   0.016446929425001144,
   0.9037898778915405,
   -1.4594221115112305,
   -1.4006901979446411,
   1.0907670259475708,
   0.6694958209991455,
   -0.07005051523447037,
   -2.7991654872894287,
   4.587980270385742,
   -1.4158998727798462,
   2.159628391265869,
   -0.5742437243461609,
   1.9995533227920532,
   -1.646377682685852,
   0.4240286350250244,
   -5.875068187713623,
   -1.6224358081817627,
   -0.6637987494468689,
   -1.101218819618225,
   -1.3241710662841797,
   2.5174007415771484,
   0.7765749096870422,
   -0.1561727374792099,
   0.39844411611557007,
   -0.5937044620513916,
   1.2973017692565918,
   -0.5107694864273071,
   0.29012638330459595,
   2.0916194915771484,
   -1.7774937152862549,
   0.5642330646514893,
   -0.09454093128442764,
   3.089550495147705,
   1.595932960510254,
   -0.11912522464990616,
   -2.906426191329956,
   -1.8795737028121948,
   -2.6446123123168945,
   -1.6688028573989868,
   1.1568225622177124,
   0.6813702583312988,
   0.642913281917572,
   -1.2991989850997925,
   -2.0079188346862793,
   -1.8603711128234863,
   0.8018338680267334,
   3.601893424987793,
   -1.188531517982483,
   4.316227436065674,
   -1.4636257886886597,
   0.8147116303443909,
   0.7188937664031982,
   -2.0012288093566895,
   1.903234601020813,
   -3.012171506881714,
   0.10468035936355591,
   2.37441086769104,
   -0.8440136313438416,
   1.4843647480010986,
   -1.025808334350586,
   3.6186940670013428,
   -1.8080449104309082,
   2.2142624855041504,
   -1.7334370613098145,
   2.128556251525879,
   0.876505970954895,
   0.3861088156700134,
   -0.5581351518630981,
   1.6071010828018188,
   1.2277648448944092,
   -0.9594826698303223,
   1.8700355291366577,
   2.4010491371154785,
   1.457556962966919,
   0.25226324796676636,
   3.711066246032715,
   2.222189426422119,
   0.3930773437023163,
   0.034287724643945694,
   -1.9815200567245483,
   3.1390843391418457,
   0.09177190065383911,
   -0.045163147151470184,
   1.6853715181350708,
   0.3910437524318695,
   -3.8334999084472656,
   3.73363995552063,
   -0.6016318798065186,
   -1.1183630228042603,
   -3.378927707672119,
   0.7728630900382996,
   -0.14082208275794983,
   -0.689363420009613,
   1.7870064973831177,
   -0.8083494305610657,
   0.913650631904602,
   0.7175709009170532,
   -1.7264180183410645,
   0.7010385394096375,
   2.7614822387695312,
   -1.0013066530227661,
   -0.5588563680648804,
   -0.08706750720739365,
   2.302727699279785,
   2.591599941253662,
   0.7891883850097656,
   -4.228740215301514,
   -2.042570114135742,
   0.7979657649993896,
   3.2580392360687256,
   1.7720222473144531,
   0.2642399072647095,
   -1.8290773630142212,
   -1.485898494720459,
   -0.0673862174153328,
   -0.0619402751326561,
   -1.0366549491882324,
   1.2258410453796387,
   -3.7354962825775146,
   -0.6399930715560913,
   -2.693885326385498,
   -0.41375309228897095,
   1.0813120603561401,
   0.2111756056547165,
   1.1539145708084106,
   1.6322386264801025,
   0.1151323989033699,
   0.7653055787086487,
   -2.908090114593506,
   0.9853371381759644,
   1.2443474531173706,
   1.7581231594085693,
   -0.6104897856712341,
   -2.9790585041046143,
   -1.7076523303985596,
   -4.290192127227783,
   0.6323803663253784,
   1.492094874382019,
   2.956387519836426,
   1.2701263427734375,
   1.0849937200546265,
   -0.2808862328529358,
   2.7686750888824463,
   -1.988599181175232,
   -2.931047201156616,
   -0.7239848375320435,
   -0.4555175304412842,
   0.09197401255369186,
   -0.3033061921596527,
   0.6785560250282288,
   -1.033571720123291,
   -2.891080379486084,
   -1.278887391090393,
   1.1157445907592773,
   -0.3323477804660797,
   0.95616215467453,
   -0.9112964868545532,
   0.6571455597877502,
   0.250777006149292,
   0.10530056059360504,
   0.734790563583374,
   1.267987847328186,
   -1.2294423580169678,
   2.6197104454040527,
   1.0791547298431396,
   -2.007716655731201,
   -0.17081952095031738,
   1.3072161674499512,
   1.4474481344223022,
   -1.2257590293884277,
   0.6097224950790405,
   1.3842737674713135,
   -1.986676573753357,
   -2.1311066150665283,
   -1.5979743003845215,
   0.0621957890689373,
   0.27621644735336304,
   0.026679573580622673,
   0.597334086894989,

In [29]:
data_list[200]

{'lpp_1943.121': [[2.3653855323791504,
   1.797225832939148,
   -1.9382015466690063,
   3.387129545211792,
   -3.5890142917633057,
   -1.122340440750122,
   0.3890557289123535,
   3.2242038249969482,
   2.1338019371032715,
   0.8671850562095642,
   -2.0759530067443848,
   -0.6305792331695557,
   1.0834239721298218,
   0.24027705192565918,
   0.09596279263496399,
   -1.6319395303726196,
   0.9258324503898621,
   1.2944040298461914,
   -1.871032953262329,
   -1.7762300968170166,
   0.019660942256450653,
   -2.7497031688690186,
   0.627681314945221,
   1.2341982126235962,
   1.4225966930389404,
   -1.71950364112854,
   -1.5930922031402588,
   -3.4457714557647705,
   -0.48372745513916016,
   2.252152919769287,
   -0.24577772617340088,
   -1.5336686372756958,
   0.732264518737793,
   -0.5448666214942932,
   1.039197564125061,
   1.0274375677108765,
   3.4383578300476074,
   0.4053836166858673,
   -0.5173530578613281,
   -0.7153807878494263,
   -0.895222544670105,
   1.1679143905639648,
   -1.0708740949630737,
   0.031342361122369766,
   4.072662830352783,
   -0.2826620638370514,
   -0.5927521586418152,
   2.160367012023926,
   2.3557283878326416,
   -2.4229745864868164,
   2.056077003479004,
   1.101073980331421,
   -0.18684732913970947,
   -0.6264136433601379,
   -0.10842211544513702,
   -0.6183912754058838,
   1.4108147621154785,
   1.5292186737060547,
   0.9117237329483032,
   2.4423487186431885,
   1.9722613096237183,
   2.432152032852173,
   2.3766026496887207,
   -0.6893873810768127,
   2.206427574157715,
   1.335379719734192,
   -1.404381513595581,
   -1.3559021949768066,
   -2.5537755489349365,
   0.32431894540786743,
   0.5720009803771973,
   -0.1676173061132431,
   0.8277276158332825,
   -0.8724769353866577,
   2.302786350250244,
   -0.981955885887146,
   -1.2110189199447632,
   3.793795108795166,
   -2.5079638957977295,
   -0.12449052929878235,
   -2.871755838394165,
   0.44136887788772583,
   -1.6305238008499146,
   0.6839591264724731,
   0.09553160518407822,
   1.7397385835647583,
   -0.4245379567146301,
   -1.1012274026870728,
   1.036478042602539,
   -1.1627717018127441,
   0.43612319231033325,
   -3.9161148071289062,
   -0.4894932806491852,
   -2.379788637161255,
   0.3672674000263214,
   -2.9907310009002686,
   0.07550344616174698,
   2.774843692779541,
   0.6142240166664124,
   2.737795352935791,
   -0.326709508895874,
   2.9129276275634766,
   -0.48917654156684875,
   -4.463962554931641,
   0.4434797465801239,
   -3.194983959197998,
   0.33747151494026184,
   2.5707316398620605,
   -2.9473752975463867,
   -0.4379611313343048,
   1.4702564477920532,
   -2.7687926292419434,
   -0.5989468097686768,
   2.7647297382354736,
   -1.33010733127594,
   -0.2077094316482544,
   -1.2581655979156494,
   -1.7020410299301147,
   -1.4456714391708374,
   1.3085176944732666,
   0.7575948238372803,
   -0.7117637395858765,
   1.8537276983261108,
   -1.7612593173980713,
   -0.839500904083252,
   1.6950122117996216,
   -0.4277837574481964,
   -0.845067024230957,
   -1.2676646709442139,
   1.1910152435302734,
   -0.32415589690208435,
   1.0945799350738525,
   -0.08816394209861755,
   -0.08105669170618057,
   -1.389664649963379,
   0.11574704945087433,
   1.4902949333190918,
   2.521500825881958,
   -0.24000468850135803,
   0.22526739537715912,
   0.5857706665992737,
   -0.3631168007850647,
   -1.3224124908447266,
   2.423180341720581,
   2.1892430782318115,
   -1.7737199068069458,
   0.21754540503025055,
   0.24069948494434357,
   -0.34153714776039124,
   2.2494618892669678,
   0.26982274651527405,
   0.8857107162475586,
   0.3339642882347107,
   -1.2837414741516113,
   -1.3893792629241943,
   -0.943808376789093,
   0.8651403188705444,
   -2.9382715225219727,
   -1.260350227355957,
   -0.3911956548690796,
   2.068890333175659,
   3.9782521724700928,
   -0.11602138727903366,
   0.22572124004364014,
   -1.3749421834945679,
   -0.027649249881505966,
   -3.0283262729644775,
   0.5693038105964661,
   1.7185901403427124,
   -2.8211185932159424,
   2.104186534881592,
   -0.3985033929347992,
   3.4071340560913086,
   0.5960950255393982,
   0.7675061225891113,
   -0.9654491543769836,
   -1.2541334629058838,
   -2.8171310424804688,
   -0.020641852170228958,
   -1.0392160415649414,
   1.075010895729065,
   2.494563579559326,
   -0.4775230586528778,
   -1.7995479106903076,
   18.331090927124023,
   3.656057357788086,
   -1.2247992753982544,
   1.2466795444488525,
   0.8256127834320068,
   1.3436360359191895,
   -1.0553672313690186,
   0.872678279876709,
   -0.6063621044158936,
   2.853620767593384,
   1.3718211650848389,
   0.07964910566806793,
   -1.945259928703308,
   -1.02066171169281,
   0.08290748298168182,
   2.2758727073669434,
   -1.1460824012756348,
   0.4193805754184723,
   1.0321022272109985,
   -0.18368172645568848,
   -0.29315921664237976,
   -0.4789811968803406,
   0.9822160601615906,
   0.014720889739692211,
   4.504453659057617,
   1.4622766971588135,
   0.8290011286735535,
   1.1040937900543213,
   -2.3616998195648193,
   0.6513791084289551,
   -2.5506279468536377,
   1.7859195470809937,
   -0.6306308507919312,
   -0.26960885524749756,
   0.8236328959465027,
   -0.3777327537536621,
   -3.322706460952759,
   1.4712709188461304,
   -0.5820240378379822,
   0.2138260453939438,
   -1.6550464630126953,
   2.1784985065460205,
   0.6350235342979431,
   1.9414256811141968,
   -1.0581287145614624,
   3.0009500980377197,
   1.4821902513504028,
   0.7027599215507507,
   1.7846742868423462,
   -3.4336729049682617,
   -0.3044153153896332,
   -0.40518224239349365,
   -3.486032009124756,
   1.8984625339508057,
   -2.278400182723999,
   2.5744330883026123,
   3.4328761100769043,
   2.584902048110962,
   -0.3012285530567169,
   1.2595014572143555,
   2.1340246200561523,
   1.8861596584320068,
   0.4275846779346466,
   -2.644645929336548,
   1.6088029146194458,
   -0.48820316791534424,
   0.11896412074565887,
   -0.6477630138397217,
   0.7613852024078369,
   5.885261058807373,
   2.4303624629974365,
   3.032667398452759,
   1.1472569704055786,
   2.0170187950134277,
   2.702083110809326,
   -0.7541646957397461,
   -0.13066108524799347,
   -0.9249253273010254,
   -1.7878916263580322,
   0.5237578749656677,
   1.4669510126113892,
   -4.446123123168945,
   1.1364656686782837,
   -0.5232642889022827,
   0.42839550971984863,
   -2.3555755615234375,
   -2.337005138397217,
   1.6583836078643799,
   -0.1388425976037979,
   -1.773494005203247,
   -0.43990764021873474,
   -2.9770655632019043,
   0.4863869249820709,
   -2.6177797317504883,
   -2.1604676246643066,
   0.6349719166755676,
   -1.3749340772628784,
   2.493539333343506,
   -0.3655962347984314,
   1.9930312633514404,
   -0.9349119067192078,
   0.09639476239681244,
   2.0762746334075928,
   0.8985525965690613,
   -2.2898247241973877,
   5.962352752685547,
   -3.809784412384033,
   2.783390522003174,
   -6.7313151359558105,
   -3.0856454372406006,
   -1.9904617071151733,
   -0.27676650881767273,
   2.488495349884033,
   -0.2336355298757553,
   1.6443194150924683,
   3.758157968521118,
   -0.19140274822711945,
   -1.088595986366272,
   0.5747758150100708,
   0.3682994544506073,
   -3.5378620624542236,
   -0.7416865229606628,
   -0.5181315541267395,
   1.5117251873016357,
   2.0610010623931885,
   1.6371185779571533,
   -4.924121856689453,
   2.5165517330169678,
   0.848177969455719,
   -2.3007800579071045,
   -1.4625073671340942,
   0.14749589562416077,
   0.4975601136684418,
   1.5642216205596924,
   -0.07739986479282379,
   -0.4776102602481842,
   -4.968388557434082,
   -1.871617078781128,
   0.7054003477096558,
   0.8551399111747742,
   0.7581140398979187,
   1.4566909074783325,
   -0.31962093710899353,
   3.1318440437316895,
   -1.5814346075057983,
   0.8388788104057312,
   -2.6089320182800293,
   0.8423780202865601,
   -3.4710464477539062,
   2.1097915172576904,
   0.34641116857528687,
   -0.9723909497261047,
   -2.49886417388916,
   -0.7483630180358887,
   -0.07539869099855423,
   -0.9061530828475952,
   -0.0010071160504594445,
   -0.5058891177177429,
   0.419734388589859,
   0.871641993522644,
   1.4499857425689697,
   0.7420510053634644,
   0.39073044061660767,
   0.5948606729507446,
   1.5028321743011475,
   1.829586386680603,
   -1.8451272249221802,
   0.12548674643039703,
   1.7256135940551758,
   -0.9300945401191711,
   0.9028932452201843,
   0.512428879737854,
   4.380241870880127,
   1.9566967487335205,
   0.4930150508880615,
   1.217316746711731,
   -3.1561286449432373,
   -0.5411499738693237,
   2.4545388221740723,
   0.01963244006037712,
   0.9682963490486145,
   -4.035917282104492,
   -5.1796369552612305,
   3.0341670513153076,
   1.5478888750076294,
   1.659969449043274,
   2.1237051486968994,
   -0.2854365408420563,
   -1.3985037803649902,
   3.6193573474884033,
   -0.8194952011108398,
   -0.18586933612823486,
   -2.8804993629455566,
   -0.8904029726982117,
   0.1704501509666443,
   4.162622451782227,
   -3.9530322551727295,
   -0.696775496006012,
   -0.4748014509677887,
   -0.9606418013572693,
   3.685044288635254,
   0.19440126419067383,
   -5.258943557739258,
   -0.4261556565761566,
   -3.9858365058898926,
   -3.537656784057617,
   -0.9398783445358276,
   0.6918370127677917,
   -0.6345664858818054,
   0.35435280203819275,
   -3.8571250438690186,
   -1.5892342329025269,
   1.6566540002822876,
   0.25888699293136597,
   1.3479799032211304,
   -0.9397372603416443,
   1.704512357711792,
   -1.0067194700241089,
   -7.109014511108398,
   -0.1352635771036148,
   -0.0859459787607193,
   -0.008785156533122063,
   12.845852851867676,
   -1.5926847457885742,
   -1.5442434549331665,
   -2.253833293914795,
   1.6344000101089478,
   1.372298002243042,
   -1.3285530805587769,
   0.6891489624977112,
   -1.7078075408935547,
   0.3113507926464081,
   -1.0305562019348145,
   4.013709545135498,
   1.9503194093704224,
   -2.3784308433532715,
   0.6975299119949341,
   -0.043396905064582825,
   0.25887933373451233,
   2.7487406730651855,
   -1.628625512123108,
   -1.5632718801498413,
   0.20543701946735382,
   -2.2851176261901855,
   -1.1445955038070679,
   -0.8844137787818909,
   -0.8835914134979248,
   0.0789995864033699,
   -0.9100325703620911,
   -0.9426052570343018,
   -1.6100265979766846,
   -2.6945440769195557,
   0.03517378121614456,
   -0.5557942986488342,
   0.9252687096595764,
   1.0736700296401978,
   -1.0903774499893188,
   1.2898492813110352,
   -1.102974534034729,
   2.986478567123413,
   -1.0924955606460571,
   0.29033800959587097,
   -1.5297532081604004,
   -0.9229913353919983,
   2.5390446186065674,
   -2.6780614852905273,
   -1.0115584135055542,
   0.15064409375190735,
   0.4907726049423218,
   -1.1642550230026245,
   2.5536110401153564,
   -1.9587839841842651,
   0.3747834265232086,
   -3.0235276222229004,
   1.1456505060195923,
   -0.9605363607406616,
   0.4782010614871979,
   0.7879917025566101,
   1.0700080394744873,
   -1.5166206359863281,
   1.0291861295700073,
   2.4471027851104736,
   1.45404851436615,
   2.2347211837768555,
   0.5771906971931458,
   0.9840911030769348,
   0.4263581931591034,
   -0.19212092459201813,
   -1.5373622179031372,
   0.4196283519268036,
   -0.5956085920333862,
   0.9378087520599365,
   5.839252471923828,
   0.4551912546157837,
   1.9645580053329468,
   0.1902393102645874,
   -1.2255821228027344,
   -1.5181005001068115,
   -3.7090024948120117,
   -1.6155937910079956,
   1.7423087358474731,
   -0.5874235033988953,
   -1.166372299194336,
   3.830909013748169,
   -1.444767951965332,
   2.6048929691314697,
   -0.26742878556251526,
   1.387416124343872,
   -1.6246652603149414,
   4.358680248260498,
   -0.29523950815200806,
   0.8947320580482483,
   -1.4074013233184814,
   1.5482360124588013,
   -1.6583987474441528,
   -1.3893485069274902,
   3.5219342708587646,
   -0.9916378259658813,
   -2.979199171066284,
   0.36783504486083984,
   -2.227151870727539,
   -1.1320339441299438,
   -1.3293920755386353,
   1.8378450870513916,
   -2.1005890369415283,
   -4.724045753479004,
   0.5842993259429932,
   1.5212210416793823,
   -0.7475828528404236,
   -1.9503602981567383,
   -0.7639623284339905,
   -0.4881761968135834,
   1.0753928422927856,
   -0.41911470890045166,
   5.925841808319092,
   -0.5178008079528809,
   -0.29774609208106995,
   0.6984245777130127,
   1.51161527633667,
   -1.1532126665115356,
   -2.6591854095458984,
   -0.9436162710189819,
   -0.3692597448825836,
   -1.5340744256973267,
   -1.0078879594802856,
   -3.411855459213257,
   2.1249234676361084,
   -0.5962368845939636,
   0.25148847699165344,
   -3.054981231689453,
   0.7198412418365479,
   -1.811626672744751,
   1.1821928024291992,
   0.6433488726615906,
   -0.21696379780769348,
   -1.6823598146438599,
   -1.9379853010177612,
   0.5574916005134583,
   0.7369508147239685,
   0.5715510845184326,
   -1.5193413496017456,
   -1.0685765743255615,
   -0.016812898218631744,
   0.9152274131774902,
   -0.7296820282936096,
   -2.9899866580963135,
   0.20200222730636597,
   0.5826638340950012,
   -0.38684093952178955,
   -2.461634635925293,
   -0.3731576204299927,
   -0.41151049733161926,
   1.2207943201065063,
   -0.5462526082992554,
   -2.175894021987915,
   1.6499638557434082,
   1.2447267770767212,
   -0.8413980007171631,
   -0.45725011825561523,
   1.3610453605651855,
   0.21115250885486603,
   -2.7503631114959717,
   -1.1606680154800415,
   -3.4080352783203125,
   -0.8374099731445312,
   0.344586580991745,
   0.5792489647865295,
   1.4365978240966797,
   -0.8730970621109009,
   2.1090123653411865,
   1.222105622291565,
   2.93203067779541,
   2.876370429992676,
   0.453183114528656,
   -0.7266279458999634,
   0.799385666847229,
   1.6982132196426392,
   -6.169248580932617,
   1.6255308389663696,
   0.4977432191371918,
   0.7746593952178955,
   0.12589144706726074,
   2.0231335163116455,
   -0.4876166880130768,
   -1.4849072694778442,
   1.5962773561477661,
   1.7254143953323364,
   -1.0334852933883667,
   -0.8163998126983643,
   -8.529394149780273,
   1.6461482048034668,
   3.4326465129852295,
   -1.8556045293807983,
   1.4664884805679321,
   0.353965163230896,
   4.022635459899902,
   -1.9968774318695068,
   -0.4713054597377777,
   2.937042236328125,
   1.8386298418045044,
   2.2075281143188477,
   -1.6414084434509277,
   -2.3190817832946777,
   1.3595870733261108,
   -0.3265797197818756,
   0.21120072901248932,
   5.340799808502197,
   -2.5963377952575684,
   -0.408649206161499,
   1.1887668371200562,
   -0.7014297842979431,
   -3.801443576812744,
   4.704700469970703,
   1.087444543838501,
   0.3173747956752777,
   -0.023092176765203476,
   -0.19330564141273499,
   0.6201633214950562,
   -0.5796850323677063,
   -2.0062787532806396,
   -4.278981685638428,
   -2.076853036880493,
   0.7907909750938416,
   -0.831038773059845,
   -1.9309298992156982,
   1.2809492349624634,
   -0.6499349474906921,
   -2.6156907081604004,
   0.9687020778656006,
   1.821883201599121,
   -0.05783228576183319,
   0.4253574311733246,
   -0.4298122823238373,
   -2.3794243335723877,
   0.4872998297214508,
   -4.0146284103393555,
   0.4112406373023987,
   20.348377227783203,
   -2.875507116317749,
   2.584299325942993,
   0.7706143260002136,
   1.640599250793457,
   2.83551287651062,
   -2.3091185092926025,
   -0.7775046825408936,
   1.926292061805725,
   2.765990972518921,
   -0.10174628347158432,
   -0.8909050226211548,
   0.4446675479412079,
   1.8417173624038696,
   0.4603075385093689,
   0.38438430428504944,
   0.061511218547821045,
   2.5259835720062256,
   2.646848201751709,
   1.4073060750961304,
   -1.5179569721221924,
   2.2949106693267822,
   0.872702956199646,
   -0.41001611948013306,
   1.9361248016357422,
   -1.709158182144165,
   0.8457871675491333,
   2.132965564727783,
   -0.3656534254550934,
   0.8411409258842468,
   1.4139809608459473,
   -0.16897062957286835,
   -0.7722145318984985,
   -1.1336333751678467,
   0.8922550082206726,
   2.9788691997528076,
   1.5204821825027466,
   0.3497518301010132,
   0.46500205993652344,
   1.257460594177246,
   1.0196537971496582,
   2.1794626712799072,
   -0.868435263633728,
   1.818006992340088,
   0.1406242400407791,
   2.3636813163757324,
   1.2309314012527466,
   2.651399612426758,
   2.2631945610046387,
   1.9860172271728516,
   0.3910442292690277,
   0.9705926775932312,
   -0.16768816113471985,
   2.3136987686157227,
   1.2866883277893066,
   -2.930680274963379,
   2.319650650024414,
   0.26573023200035095,
   -1.117301106452942,
   -2.637516498565674,
   -1.1236690282821655,
   -0.6733406186103821,
   -0.09370261430740356,
   -1.0801995992660522,
   -2.415942430496216,
   1.246130347251892,
   -0.4589613676071167,
   -1.3070734739303589,
   2.1656494140625,
   -0.26807287335395813,
   -3.302997350692749,
   4.504757404327393,
   1.9035747051239014,
   -3.2795822620391846,
   2.217437982559204,
   1.916064739227295,
   0.7032120823860168,
   -2.2325942516326904,
   -1.223842978477478,
   0.11667905002832413,
   1.9148703813552856,
   -0.4559759795665741,
   -0.3006059229373932,
   -0.2215510606765747,
   -0.8189045786857605,
   0.9425549507141113,
   -0.505237877368927,
   -0.750224232673645,
   1.7946677207946777,
   -0.11135438084602356,
   -3.4467101097106934,
   -0.8876368999481201,
   -0.010781696997582912,
   2.1577744483947754,
   -1.5580816268920898,
   3.181394577026367,
   0.569852888584137,
   -0.769463837146759,
   -2.4787662029266357,
   3.3564000129699707,
   2.294095277786255,
   0.2224821299314499,
   -3.1299514770507812,
   1.5204180479049683,
   -1.7358309030532837,
   -1.6549053192138672,
   2.248926877975464,
   -0.5411095023155212,
   2.8676810264587402,
   1.9489026069641113,
   -0.5371825695037842,
   -0.8009604811668396,
   -2.9755852222442627,
   -1.6835002899169922,
   -0.29253458976745605,
   -2.2204911708831787,
   2.0975828170776367,
   1.5839078426361084,
   -1.0218778848648071,
   -2.93920636177063,
   0.20130951702594757,
   -0.08449196815490723,
   -1.3245171308517456,
   1.158567190170288,
   2.7603917121887207,
   2.5065391063690186,
   -0.8972299695014954,
   -0.2263975739479065,
   -1.0707989931106567,
   1.1450884342193604,
   -0.8242895007133484,
   2.540532112121582,
   -1.1270766258239746,
   0.4065708816051483,
   -1.2729936838150024,
   0.7178354859352112,
   0.3786516487598419,
   -1.846791386604309,
   -0.488339900970459,
   -1.2497773170471191,
   2.087631940841675,
   19.066438674926758,
   0.808675229549408,
   -0.8206058740615845,
   -2.353768825531006,
   -1.729370355606079,
   -1.078885793685913,
   1.0906715393066406,
   3.5318078994750977,
   -2.021613836288452,
   -1.0224614143371582,
   0.8549103736877441,
   -0.40682217478752136,
   -0.23429059982299805,
   1.26956045627594,
   -0.6830976009368896,
   -1.025431513786316,
   -1.9697636365890503,
   -3.5590338706970215,
   -0.4487631916999817,
   -2.360029697418213,
   -3.3783466815948486,
   0.4359467923641205,
   -2.4677233695983887,
   -1.8608790636062622,
   0.09669982641935349,
   1.277147650718689,
   -1.221251130104065,
   -0.13316474854946136,
   -4.082035064697266,
   -3.7014636993408203,
   0.612034261226654,
   1.6664540767669678,
   -0.0783093199133873,
   0.17359012365341187,
   -2.1290509700775146,
   -1.3342987298965454,
   -0.7367681264877319,
   1.6935065984725952,
   0.7241748571395874,
   1.6735223531723022,
   0.0381116159260273,
   2.1876025199890137,
   1.059273362159729,
   -0.31245681643486023,
   0.5931436419487,
   0.19353607296943665,
   0.8471430540084839,
   1.8890225887298584,
   -0.3833318054676056,
   3.139709711074829,
   -1.4240905046463013,
   0.2845419645309448,
   0.6679331064224243,
   0.03202500939369202,
   -0.10685761272907257,
   -1.4195657968521118,
   0.09945819526910782,
   1.9290452003479004,
   0.723222017288208,
   -1.3633294105529785,
   0.3645472824573517,
   1.0646252632141113,
   1.30843186378479,
   2.2238364219665527,
   1.5582271814346313,
   -1.9767427444458008,
   2.651608467102051,
   0.16855554282665253,
   5.802765369415283,
   -1.4434850215911865,
   -1.2403144836425781,

In [30]:
len(data_list)

476

In [17]:
train_data['lpp_1943.12']['frightened-2'].keys()

dict_keys(['LABEL', 'ARGM-CAU', 'ARGM-MOD', 'ARG1', 'EVENT', 'ARG0'])

In [39]:
len(data_list[5]['lpp_1943.24'])

13

In [ ]:
len(data_list[1]['lpp_1943.12'])

11

In [7]:
len(data_list[1]['lpp_1943.12'][0])

4096

In [43]:
ids_in_data = set()

for d in data_list:
    for k in d:
        ids_in_data.add(k)

In [44]:
ids_in_data

{'DF-170-181103-888_2529.11',
 'DF-170-181104-872_8783.2',
 'DF-170-181104-872_8783.4',
 'DF-170-181104-872_8783.9',
 'DF-170-181110-876_5210.10',
 'DF-170-181122-878_0223.4',
 'DF-199-192794-661_2918.1',
 'DF-200-192400-625_6304.14',
 'DF-200-192400-625_6344.2',
 'DF-200-192400-625_7557.13',
 'DF-200-192403-625_0370.7',
 'DF-200-192448-618_9851.49',
 'DF-200-192448-618_9851.62',
 'bolt-eng-DF-170-181103-8882529_0097.25',
 'bolt-eng-DF-170-181103-8883379_0035.6',
 'bolt-eng-DF-170-181103-8883574_0105.12',
 'bolt-eng-DF-170-181103-8883574_0105.13',
 'bolt-eng-DF-170-181103-8883574_0105.14',
 'bolt-eng-DF-170-181103-8883574_0105.15',
 'bolt-eng-DF-170-181103-8883574_0105.16',
 'bolt-eng-DF-170-181103-8883574_0105.18',
 'bolt-eng-DF-170-181103-8883574_0105.22',
 'bolt-eng-DF-170-181103-8883574_0105.6',
 'bolt-eng-DF-170-181103-8883574_0105.9',
 'bolt-eng-DF-170-181103-8883574_0186.1',
 'bolt-eng-DF-170-181103-8884342_0086.13',
 'bolt-eng-DF-170-181103-8884342_0086.17',
 'bolt-eng-DF-170-181103-8886126_0016.1',
 'bolt-eng-DF-170-181103-8886126_0016.13',
 'bolt-eng-DF-170-181103-8886126_0016.2',
 'bolt-eng-DF-170-181103-8886126_0016.5',
 'bolt-eng-DF-170-181103-8886126_0017.1',
 'bolt-eng-DF-170-181103-8886126_0017.2',
 'bolt-eng-DF-170-181103-8886126_0017.4',
 'bolt-eng-DF-170-181103-8886126_0017.5',
 'bolt-eng-DF-170-181103-8886126_0017.6',
 'bolt-eng-DF-170-181103-8886126_0017.7',
 'bolt-eng-DF-170-181103-8886126_0017.8',
 'bolt-eng-DF-170-181103-8886574_0090.2',
 'bolt-eng-DF-170-181103-8888447_0044.14',
 'bolt-eng-DF-170-181103-8888447_0058.4',
 'bolt-eng-DF-170-181103-8888447_0059.2',
 'bolt-eng-DF-170-181103-8888447_0059.21',
 'bolt-eng-DF-170-181103-8888447_0059.26',
 'bolt-eng-DF-170-181103-8888447_0059.27',
 'bolt-eng-DF-170-181103-8888447_0059.28',
 'bolt-eng-DF-170-181103-8888447_0059.29',
 'bolt-eng-DF-170-181103-8889109_0047.4',
 'bolt-eng-DF-170-181103-8889109_0073.18',
 'bolt-eng-DF-170-181103-8889109_0074.14',
 'bolt-eng-DF-170-181103-8889109_0078.17',
 'bolt-eng-DF-170-181103-8889109_0078.18',
 'bolt-eng-DF-170-181103-8889109_0078.19',
 'bolt-eng-DF-170-181103-8889109_0078.20',
 'bolt-eng-DF-170-181103-8889109_0078.21',
 'bolt-eng-DF-170-181103-8889674_0058.1',
 'bolt-eng-DF-170-181103-8889674_0058.2',
 'bolt-eng-DF-170-181103-8889674_0058.3',
 'bolt-eng-DF-170-181103-8889674_0058.4',
 'bolt-eng-DF-170-181103-8889674_0058.5',
 'bolt-eng-DF-170-181103-8889674_0058.6',
 'bolt-eng-DF-170-181103-8889674_0058.7',
 'bolt-eng-DF-170-181103-8889674_0059.13',
 'bolt-eng-DF-170-181103-8889674_0059.14',
 'bolt-eng-DF-170-181103-8889674_0059.15',
 'bolt-eng-DF-170-181103-8889674_0059.16',
 'bolt-eng-DF-170-181103-8889674_0060.14',
 'bolt-eng-DF-170-181103-8890103_0098.15',
 'bolt-eng-DF-170-181103-8890653_0146.1',
 'bolt-eng-DF-170-181103-8890653_0146.3',
 'bolt-eng-DF-170-181103-8890653_0146.4',
 'bolt-eng-DF-170-181103-8891686_0018.15',
 'bolt-eng-DF-170-181103-8891686_0020.15',
 'bolt-eng-DF-170-181103-8891686_0020.16',
 'bolt-eng-DF-170-181103-8891686_0021.7',
 'bolt-eng-DF-170-181103-8892003_0048.4',
 'bolt-eng-DF-170-181103-8892003_0048.6',
 'bolt-eng-DF-170-181103-8892003_0048.7',
 'bolt-eng-DF-170-181103-8892003_0048.8',
 'bolt-eng-DF-170-181103-8892003_0048.9',
 'bolt-eng-DF-170-181103-8892003_0049.1',
 'bolt-eng-DF-170-181103-8892003_0049.2',
 'bolt-eng-DF-170-181103-8892003_0049.3',
 'bolt-eng-DF-170-181105-8850361_0027.2',
 'bolt-eng-DF-170-181105-8850361_0028.15',
 'bolt-eng-DF-170-181105-8850361_0028.16',
 'bolt-eng-DF-170-181105-8850361_0028.17',
 'bolt-eng-DF-170-181105-8850361_0028.18',
 'bolt-eng-DF-170-181105-8850361_0028.19',
 'bolt-eng-DF-170-181105-8850361_0028.20',
 'bolt-eng-DF-170-181105-8850361_0028.21',
 'bolt-eng-DF-170-181105-8850361_0028.22',
 'bolt-eng-DF-170-181105-8850361_0028.23',
 'bolt-eng-DF-170-181105-8850361_0028.25',
 'bolt-eng-DF-170-181105-8850361_0028.26',
 'bolt-eng-DF-170-181105-8850361_0028.27',
 'bolt-eng-DF-170-181105-8850361_0028.28',
 'bolt-eng-DF-170-181105-8850361_0028.29',
 'bolt-eng-DF-170-181105-8850361_0028.30',
 'bolt-eng-DF-170-181105-8850361_0028.31',
 'bolt-eng-DF-170-181105-8850361_0028.32',
 'bolt-eng-DF-170-181105-8850361_0028.33',
 'bolt-eng-DF-170-181118-8875443_0128.15',
 'bolt-eng-DF-170-181118-8875443_0128.20',
 'bolt-eng-DF-170-181118-8875443_0366.11',
 'bolt-eng-DF-170-181118-8875443_0366.12',
 'bolt-eng-DF-170-181118-8875443_0367.10',
 'bolt-eng-DF-170-181118-8875443_0367.3',
 'bolt-eng-DF-170-181118-8875443_0367.7',
 'bolt-eng-DF-170-181118-8875443_0369.11',
 'bolt-eng-DF-170-181118-8875443_0369.15',
 'bolt-eng-DF-170-181122-8787903_0048.1',
 'bolt-eng-DF-170-181122-8787903_0048.10',
 'bolt-eng-DF-170-181122-8787903_0048.11',
 'bolt-eng-DF-170-181122-8787903_0048.12',
 'bolt-eng-DF-170-181122-8787903_0048.13',
 'bolt-eng-DF-170-181122-8787903_0048.15',
 'bolt-eng-DF-170-181122-8787903_0048.2',
 'bolt-eng-DF-170-181122-8787903_0048.3',
 'bolt-eng-DF-170-181122-8787903_0048.4',
 'bolt-eng-DF-170-181122-8787903_0048.5',
 'bolt-eng-DF-170-181122-8787903_0048.6',
 'bolt-eng-DF-170-181122-8787903_0048.7',
 'bolt-eng-DF-170-181122-8787903_0048.8',
 'bolt-eng-DF-170-181122-8787903_0048.9',
 'bolt-eng-DF-170-181122-8787903_0049.1',
 'bolt-eng-DF-170-181122-8787903_0049.2',
 'bolt-eng-DF-170-181122-8787903_0049.3',
 'bolt-eng-DF-170-181122-8787903_0049.4',
 'bolt-eng-DF-170-181122-8787903_0049.5',
 'bolt-eng-DF-170-181122-8787903_0049.6',
 'bolt-eng-DF-170-181122-8787903_0049.7',
 'bolt-eng-DF-170-181122-8787903_0052.2',
 'bolt-eng-DF-201-185510-351190_0079.25',
 'bolt-eng-DF-201-185510-351190_0079.28',
 'bolt-eng-DF-201-185510-351190_0079.34',
 'bolt-eng-DF-201-185510-351190_0310.1',
 'bolt-eng-DF-201-185510-351190_0310.10',
 'bolt-eng-DF-201-185510-351190_0310.11',
 'bolt-eng-DF-201-185510-351190_0310.12',
 'bolt-eng-DF-201-185510-351190_0310.13',
 'bolt-eng-DF-201-185510-351190_0310.14',
 'bolt-eng-DF-201-185510-351190_0310.16',
 'bolt-eng-DF-201-185510-351190_0310.17',
 'bolt-eng-DF-201-185510-351190_0310.18',
 'bolt-eng-DF-201-185510-351190_0310.19',
 'bolt-eng-DF-201-185510-351190_0310.2',
 'bolt-eng-DF-201-185510-351190_0310.20',
 'bolt-eng-DF-201-185510-351190_0310.21',
 'bolt-eng-DF-201-185510-351190_0310.22',
 'bolt-eng-DF-201-185510-351190_0310.23',
 'bolt-eng-DF-201-185510-351190_0310.24',
 'bolt-eng-DF-201-185510-351190_0310.25',
 'bolt-eng-DF-201-185510-351190_0310.26',
 'bolt-eng-DF-201-185510-351190_0310.33',
 'bolt-eng-DF-201-185510-351190_0310.35',
 'bolt-eng-DF-201-185510-351190_0310.38',
 'bolt-eng-DF-201-185510-351190_0310.4',
 'bolt-eng-DF-201-185510-351190_0310.43',
 'bolt-eng-DF-201-185510-351190_0310.5',
 'bolt-eng-DF-201-185510-351190_0310.6',
 'bolt-eng-DF-201-185510-351190_0310.7',
 'bolt-eng-DF-201-185510-351190_0310.8',
 'bolt-eng-DF-201-185510-351190_0310.9',
 'bolt-eng-DF-201-185510-351190_0311.1',
 'bolt-eng-DF-201-185510-351190_0311.2',
 'bolt-eng-DF-201-185510-351190_0311.3',
 'bolt-eng-DF-201-185510-351190_0311.4',
 'bolt-eng-DF-201-185510-351190_0311.5',
 'bolt-eng-DF-201-185510-351190_0311.6',
 'lpp_1943.1',
 'lpp_1943.100',
 'lpp_1943.101',
 'lpp_1943.102',
 'lpp_1943.104',
 'lpp_1943.105',
 'lpp_1943.106',
 'lpp_1943.107',
 'lpp_1943.109',
 'lpp_1943.112',
 'lpp_1943.113',
 'lpp_1943.114',
 'lpp_1943.115',
 'lpp_1943.117',
 'lpp_1943.118',
 'lpp_1943.119',
 'lpp_1943.12',
 'lpp_1943.120',
 'lpp_1943.121',
 'lpp_1943.124',
 'lpp_1943.125',
 'lpp_1943.126',
 'lpp_1943.127',
 'lpp_1943.128',
 'lpp_1943.129',
 'lpp_1943.130',
 'lpp_1943.131',
 'lpp_1943.132',
 'lpp_1943.133',
 'lpp_1943.135',
 'lpp_1943.136',
 'lpp_1943.138',
 'lpp_1943.139',
 'lpp_1943.140',
 'lpp_1943.142',
 'lpp_1943.21',
 'lpp_1943.22',
 'lpp_1943.23',
 'lpp_1943.24',
 'lpp_1943.25',
 'lpp_1943.26',
 'lpp_1943.27',
 'lpp_1943.28',
 'lpp_1943.29',
 'lpp_1943.30',
 'lpp_1943.31',
 'lpp_1943.32',
 'lpp_1943.33',
 'lpp_1943.34',
 'lpp_1943.35',
 'lpp_1943.37',
 'lpp_1943.38',
 'lpp_1943.39',
 'lpp_1943.40',
 'lpp_1943.41',
 'lpp_1943.42',
 'lpp_1943.43',
 'lpp_1943.44',
 'lpp_1943.45',
 'lpp_1943.46',
 'lpp_1943.47',
 'lpp_1943.48',
 'lpp_1943.49',
 'lpp_1943.50',
 'lpp_1943.51',
 'lpp_1943.52',
 'lpp_1943.53',
 'lpp_1943.54',
 'lpp_1943.55',
 'lpp_1943.56',
 'lpp_1943.57',
 'lpp_1943.58',
 'lpp_1943.59',
 'lpp_1943.60',
 'lpp_1943.604',
 'lpp_1943.607',
 'lpp_1943.609',
 'lpp_1943.61',
 'lpp_1943.610',
 'lpp_1943.611',
 'lpp_1943.612',
 'lpp_1943.613',
 'lpp_1943.614',
 'lpp_1943.615',
 'lpp_1943.616',
 'lpp_1943.617',
 'lpp_1943.618',
 'lpp_1943.619',
 'lpp_1943.62',
 'lpp_1943.620',
 'lpp_1943.621',
 'lpp_1943.622',
 'lpp_1943.623',
 'lpp_1943.624',
 'lpp_1943.625',
 'lpp_1943.626',
 'lpp_1943.627',
 'lpp_1943.628',
 'lpp_1943.629',
 'lpp_1943.63',
 'lpp_1943.630',
 'lpp_1943.631',
 'lpp_1943.632',
 'lpp_1943.633',
 'lpp_1943.64',
 'lpp_1943.649',
 'lpp_1943.65',
 'lpp_1943.650',
 'lpp_1943.651',
 'lpp_1943.652',
 'lpp_1943.653',
 'lpp_1943.654',
 'lpp_1943.655',
 'lpp_1943.656',
 'lpp_1943.657',
 'lpp_1943.658',
 'lpp_1943.659',
 'lpp_1943.66',
 'lpp_1943.660',
 'lpp_1943.662',
 'lpp_1943.663',
 'lpp_1943.665',
 'lpp_1943.666',
 'lpp_1943.667',
 'lpp_1943.668',
 'lpp_1943.669',
 'lpp_1943.67',
 'lpp_1943.670',
 'lpp_1943.671',
 'lpp_1943.672',
 'lpp_1943.673',
 'lpp_1943.674',
 'lpp_1943.675',
 'lpp_1943.677',
 'lpp_1943.678',
 'lpp_1943.679',
 'lpp_1943.680',
 'lpp_1943.683',
 'lpp_1943.686',
 'lpp_1943.689',
 'lpp_1943.69',
 'lpp_1943.690',
 'lpp_1943.691',
 'lpp_1943.693',
 'lpp_1943.694',
 'lpp_1943.696',
 'lpp_1943.697',
 'lpp_1943.698',
 'lpp_1943.699',
 'lpp_1943.70',
 'lpp_1943.700',
 'lpp_1943.703',
 'lpp_1943.704',
 'lpp_1943.706',
 'lpp_1943.707',
 'lpp_1943.709',
 'lpp_1943.710',
 'lpp_1943.711',
 'lpp_1943.713',
 'lpp_1943.714',
 'lpp_1943.715',
 'lpp_1943.716',
 'lpp_1943.717',
 'lpp_1943.718',
 'lpp_1943.719',
 'lpp_1943.72',
 'lpp_1943.720',
 'lpp_1943.722',
 'lpp_1943.723',
 'lpp_1943.724',
 'lpp_1943.725',
 'lpp_1943.726',
 'lpp_1943.727',
 'lpp_1943.728',
 'lpp_1943.729',
 'lpp_1943.73',
 'lpp_1943.732',
 'lpp_1943.733',
 'lpp_1943.734',
 'lpp_1943.735',
 'lpp_1943.737',
 'lpp_1943.738',
 'lpp_1943.739',
 'lpp_1943.74',
 'lpp_1943.740',
 'lpp_1943.742',
 'lpp_1943.743',
 'lpp_1943.745',
 'lpp_1943.746',
 'lpp_1943.747',
 'lpp_1943.748',
 'lpp_1943.749',
 'lpp_1943.75',
 'lpp_1943.750',
 'lpp_1943.751',
 'lpp_1943.752',
 'lpp_1943.753',
 'lpp_1943.76',
 'lpp_1943.77',
 'lpp_1943.78',
 'lpp_1943.79',
 'lpp_1943.80',
 'lpp_1943.81',
 'lpp_1943.83',
 'lpp_1943.84',
 'lpp_1943.85',
 'lpp_1943.86',
 'lpp_1943.87',
 'lpp_1943.88',
 'lpp_1943.89',
 'lpp_1943.90',
 'lpp_1943.92',
 'lpp_1943.94',
 'lpp_1943.95',
 'lpp_1943.96',
 'lpp_1943.97',
 'lpp_1943.99',
 'minecraft-4-4-table2-b29-a8_1167.1',
 'minecraft-4-4-table2-b29-a8_1167.10',
 'minecraft-4-4-table2-b29-a8_1167.11',
 'minecraft-4-4-table2-b29-a8_1167.12',
 'minecraft-4-4-table2-b29-a8_1167.13',
 'minecraft-4-4-table2-b29-a8_1167.14',
 'minecraft-4-4-table2-b29-a8_1167.15',
 'minecraft-4-4-table2-b29-a8_1167.16',
 'minecraft-4-4-table2-b29-a8_1167.17',
 'minecraft-4-4-table2-b29-a8_1167.18',
 'minecraft-4-4-table2-b29-a8_1167.19',
 'minecraft-4-4-table2-b29-a8_1167.2',
 'minecraft-4-4-table2-b29-a8_1167.20',
 'minecraft-4-4-table2-b29-a8_1167.21',
 'minecraft-4-4-table2-b29-a8_1167.22',
 'minecraft-4-4-table2-b29-a8_1167.23',
 'minecraft-4-4-table2-b29-a8_1167.24',
 'minecraft-4-4-table2-b29-a8_1167.25',
 'minecraft-4-4-table2-b29-a8_1167.26',
 'minecraft-4-4-table2-b29-a8_1167.27',
 'minecraft-4-4-table2-b29-a8_1167.28',
 'minecraft-4-4-table2-b29-a8_1167.3',
 'minecraft-4-4-table2-b29-a8_1167.4',
 'minecraft-4-4-table2-b29-a8_1167.5',
 'minecraft-4-4-table2-b29-a8_1167.6',
 'minecraft-4-4-table2-b29-a8_1167.7',
 'minecraft-4-4-table2-b29-a8_1167.8',
 'minecraft-4-4-table2-b29-a8_1167.9',
 'minecraft-4-6-3d-triangle_1245.1',
 'minecraft-4-6-3d-triangle_1245.10',
 'minecraft-4-6-3d-triangle_1245.11',
 'minecraft-4-6-3d-triangle_1245.12',
 'minecraft-4-6-3d-triangle_1245.13',
 'minecraft-4-6-3d-triangle_1245.14',
 'minecraft-4-6-3d-triangle_1245.15',
 'minecraft-4-6-3d-triangle_1245.16',
 'minecraft-4-6-3d-triangle_1245.17',
 'minecraft-4-6-3d-triangle_1245.18',
 'minecraft-4-6-3d-triangle_1245.19',
 'minecraft-4-6-3d-triangle_1245.2',
 'minecraft-4-6-3d-triangle_1245.20',
 'minecraft-4-6-3d-triangle_1245.21',
 'minecraft-4-6-3d-triangle_1245.22',
 'minecraft-4-6-3d-triangle_1245.23',
 'minecraft-4-6-3d-triangle_1245.24',
 'minecraft-4-6-3d-triangle_1245.25',
 'minecraft-4-6-3d-triangle_1245.26',
 'minecraft-4-6-3d-triangle_1245.27',
 'minecraft-4-6-3d-triangle_1245.28',
 'minecraft-4-6-3d-triangle_1245.29',
 'minecraft-4-6-3d-triangle_1245.3',
 'minecraft-4-6-3d-triangle_1245.30',
 'minecraft-4-6-3d-triangle_1245.31',
 'minecraft-4-6-3d-triangle_1245.32',
 'minecraft-4-6-3d-triangle_1245.4',
 'minecraft-4-6-3d-triangle_1245.5',
 'minecraft-4-6-3d-triangle_1245.6',
 'minecraft-4-6-3d-triangle_1245.7',
 'minecraft-4-6-3d-triangle_1245.8',
 'minecraft-4-6-3d-triangle_1245.9',
 'wb.p2.5_c2e_0037.1',
 'wb.p2.5_c2e_0037.10',
 'wb.p2.5_c2e_0037.11',
 'wb.p2.5_c2e_0037.2',
 'wb.p2.5_c2e_0037.3',
 'wb.p2.5_c2e_0037.4',
 'wb.p2.5_c2e_0037.5',
 'wb.p2.5_c2e_0037.6',
 'wb.p2.5_c2e_0037.7',
 'wb.p2.5_c2e_0037.8',
 'wb.p2.5_c2e_0037.9',
 'wb.p2.5_c2e_0046.1',
 'wb.p2.5_c2e_0046.10',
 'wb.p2.5_c2e_0046.2',
 'wb.p2.5_c2e_0046.3',
 'wb.p2.5_c2e_0046.4',
 'wb.p2.5_c2e_0046.5',
 'wb.p2.5_c2e_0046.6',
 'wb.p2.5_c2e_0046.7',
 'wb.p2.5_c2e_0046.8',
 'wb.p2.5_c2e_0046.9',
 'wb.p2.5_c2e_0069.1',
 'wb.p2.5_c2e_0069.2',
 'wb.p2.5_c2e_0069.3',
 'wb.p2.5_c2e_0069.4',
 'web1-eng-DF-241-201379-5514596_0001.1',
 'web1-eng-DF-241-201379-5514596_0001.2',
 'web1-eng-DF-241-201379-5514596_0002.1',
 'web1-eng-DF-241-201379-5514596_0003.2'}

In [ ]:
x

login(token=HUGGING_FACE_LOGIN_TOKEN)

In [11]:
from transformers import AutoTokenizer, AutoModel

MODEL_NAME = "meta-llama/Llama-3.1-8B"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

OSError: You are trying to access a gated repo.
Make sure to have access to it at https://huggingface.co/meta-llama/Llama-3.1-8B.
403 Client Error. (Request ID: Root=1-69a886b8-693d56a22c94ba9415910bb6;048bab2f-203f-4429-93a9-b602526b673d)

Cannot access gated repo for url https://huggingface.co/meta-llama/Llama-3.1-8B/resolve/main/config.json.
Access to model meta-llama/Llama-3.1-8B is restricted and you are not in the authorized list. Visit https://huggingface.co/meta-llama/Llama-3.1-8B to ask for access.

In [2]:
df = pd.read_csv("../GraphSpect/classifier_data/combinedFinalized.csv")

In [3]:
len(df)

1473

In [4]:
df.head()

,id,context,sentence,graph,variable_name,predicate,broad_aspect_1,broad_aspect_2,broad_aspect_3,broad_aspect_4,broad_aspect_5,adjudicated,second_choice_adjudicated,compare,alignment,flag,reason_for_flag
0,lpp_1943.1,NaN,Chapter 1 .,(s1p / publication-91\n :ARG1 (s1c / chapt...,s1p,publication-91,none,none,NaN,NaN,NaN,none,NaN,True,s1p: 0-0; s1c: 1-1; s1o: 2-2; s1t: 0-0,False,NaN
1,lpp_1943.12,"But they answered : "" Frighten ?","Why should any one be frightened by a hat ? """,(s12s / say-91\n :ARG0 (s12p2 / person)\n...,s12s,say-91,none,performance,performance,NaN,NaN,performance,NaN,False,s12s: 0-0; s12p2: 0-0; s12f: 6-6; s12h: 9-9; s...,False,NaN
2,lpp_1943.12,"But they answered : "" Frighten ?","Why should any one be frightened by a hat ? """,(s12s / say-91\n :ARG0 (s12p2 / person)\n...,s12f,frighten-01,state,state,NaN,NaN,NaN,state,NaN,True,s12s: 0-0; s12p2: 0-0; s12f: 6-6; s12h: 9-9; s...,False,NaN
3,lpp_1943.21,Grown - ups never understand anything by thems...,"So then I chose another profession , and learn...",(s21h / have-reason-91\n :ARG1 (s21a / an...,s21h,have-reason-91,none,none,NaN,NaN,NaN,none,NaN,True,s21h: 0-0; s21a: 8-8; s21c: 4-4; s21i: 3-3; s2...,False,NaN
4,lpp_1943.21,Grown - ups never understand anything by thems...,"So then I chose another profession , and learn...",(s21h / have-reason-91\n :ARG1 (s21a / an...,s21c,choose-01,performance,performance,NaN,NaN,NaN,performance,NaN,True,s21h: 0-0; s21a: 8-8; s21c: 4-4; s21i: 3-3; s2...,False,NaN

In [5]:
df[df['id'] == 'lpp_1943.610']

,id,context,sentence,graph,variable_name,predicate,broad_aspect_1,broad_aspect_2,broad_aspect_3,broad_aspect_4,broad_aspect_5,adjudicated,second_choice_adjudicated,compare,alignment,flag,reason_for_flag
53,lpp_1943.610,""" Good morning , "" said the little prince .",""" That is a queer hat you are wearing . """,(s610h2 / hat\n :mod (s610q2 / queer)\n...,s610w2,wear-01,state,state,NaN,NaN,NaN,state,NaN,True,s610h2: 6-6; s610q2: 5-5; s610t2: 2-2; s610w2:...,False,NaN

In [6]:
print(df[df['id'] == 'lpp_1943.610'].iloc[0]['graph'])

(s610h2 / hat
        :mod (s610q2 / queer)
        :domain (s610t2 / that)
        :ARG1-of (s610w2 / wear-01))

In [70]:
len(data_list[1]['lpp_1943.12'])

11

In [88]:
torch.tensor(data_list[1]['lpp_1943.12']).shape

torch.Size([11, 4096])

In [97]:
torch.sum(torch.tensor(data_list[1]['lpp_1943.12'][2:6]), dim=0).shape

torch.Size([4096])

In [ ]:
torch.sum()

In [91]:
node_data = torch.tensor([])

In [94]:
node_data.shape

torch.Size([0])

In [102]:
torch.cat((node_data, torch.sum(torch.tensor(data_list[1]['lpp_1943.12']), dim=0).unsqueeze(0))).shape

torch.Size([1, 4096])

In [195]:
temp = torch.sum(torch.tensor(data_list[1]['lpp_1943.12'])[:3], dim=0)

In [205]:
torch.sum(torch.cat((temp.unsqueeze(0), temp.unsqueeze(0))), dim=0).shape

torch.Size([4096])

In [204]:
torch.cat((temp.unsqueeze(0), temp.unsqueeze(0))).shape

torch.Size([2, 4096])

In [ ]:
temp.unsqueeze(0)

torch.Size([1, 1, 4096])

In [69]:
df[df['id'] == 'lpp_1943.12'].iloc[0]['sentence']

' Why should any one be frightened by a hat ? "'

In [68]:
len(df[df['id'] == 'lpp_1943.12'].iloc[0]['sentence'].split())

11

In [187]:
df[df['id'] == 'lpp_1943.12']

,id,context,sentence,graph,variable_name,predicate,broad_aspect_1,broad_aspect_2,broad_aspect_3,broad_aspect_4,broad_aspect_5,adjudicated,second_choice_adjudicated,compare,alignment,flag,reason_for_flag
1,lpp_1943.12,"But they answered : "" Frighten ?","Why should any one be frightened by a hat ? """,(s12s / say-91\n :ARG0 (s12p2 / person)\n...,s12s,say-91,none,performance,performance,NaN,NaN,performance,NaN,False,s12s: 0-0; s12p2: 0-0; s12f: 6-6; s12h: 9-9; s...,False,NaN
2,lpp_1943.12,"But they answered : "" Frighten ?","Why should any one be frightened by a hat ? """,(s12s / say-91\n :ARG0 (s12p2 / person)\n...,s12f,frighten-01,state,state,NaN,NaN,NaN,state,NaN,True,s12s: 0-0; s12p2: 0-0; s12f: 6-6; s12h: 9-9; s...,False,NaN

In [186]:
len(df[df['id'] == 'lpp_1943.12'])

2

In [74]:
df[df['id'] == 'lpp_1943.12'].iloc[0]['alignment']

's12s: 0-0; s12p2: 0-0; s12f: 6-6; s12h: 9-9; s12a: 3-3; s12u: 1-1; s12s: 11-11; s12p3: 0-0'

In [77]:
print(df[df['id'] == 'lpp_1943.12'].iloc[0]['graph'])

(s12s / say-91
      :ARG0 (s12p2 / person)
      :ARG1 (s12f / frighten-01
                  :ARG0 (s12h / hat)
                  :ARG1 (s12p / person
                              :mod (s12a / any)
                              :refer-person 3rd
                              :refer-number singular)
                  :reason (s12u / umr-unknown)
                  :quote s12s)
      :ARG2 (s12p3 / person))

In [71]:
df[df['id'] == 'lpp_1943.12'].iloc[0]['sentence'].split()

['Why', 'should', 'any', 'one', 'be', 'frightened', 'by', 'a', 'hat', '?', '"']

In [78]:
g = penman.decode(df[df['id'] == 'lpp_1943.12'].iloc[0]['graph'])

In [79]:
g.instances()

[Instance(source='s12s', role=':instance', target='say-91'),
 Instance(source='s12p2', role=':instance', target='person'),
 Instance(source='s12f', role=':instance', target='frighten-01'),
 Instance(source='s12h', role=':instance', target='hat'),
 Instance(source='s12p', role=':instance', target='person'),
 Instance(source='s12a', role=':instance', target='any'),
 Instance(source='s12u', role=':instance', target='umr-unknown'),
 Instance(source='s12p3', role=':instance', target='person')]

In [82]:
g.edges()

[Edge(source='s12s', role=':ARG0', target='s12p2'),
 Edge(source='s12s', role=':ARG1', target='s12f'),
 Edge(source='s12f', role=':ARG0', target='s12h'),
 Edge(source='s12f', role=':ARG1', target='s12p'),
 Edge(source='s12p', role=':mod', target='s12a'),
 Edge(source='s12f', role=':reason', target='s12u'),
 Edge(source='s12f', role=':quote', target='s12s'),
 Edge(source='s12s', role=':ARG2', target='s12p3')]

In [81]:
g.triples

[('s12s', ':instance', 'say-91'),
 ('s12s', ':ARG0', 's12p2'),
 ('s12p2', ':instance', 'person'),
 ('s12s', ':ARG1', 's12f'),
 ('s12f', ':instance', 'frighten-01'),
 ('s12f', ':ARG0', 's12h'),
 ('s12h', ':instance', 'hat'),
 ('s12f', ':ARG1', 's12p'),
 ('s12p', ':instance', 'person'),
 ('s12p', ':mod', 's12a'),
 ('s12a', ':instance', 'any'),
 ('s12p', ':refer-person', '3rd'),
 ('s12p', ':refer-number', 'singular'),
 ('s12f', ':reason', 's12u'),
 ('s12u', ':instance', 'umr-unknown'),
 ('s12f', ':quote', 's12s'),
 ('s12s', ':ARG2', 's12p3'),
 ('s12p3', ':instance', 'person')]

In [42]:
df['id'].value_counts()

id
bolt-eng-DF-170-181105-8850361_0028.27    18
bolt-eng-DF-170-181105-8850361_0028.31    18
wb.p2.5_c2e_0046.5                        15
wb.p2.5_c2e_0037.1                        14
bolt-eng-DF-170-181122-8787903_0048.6     14
                                          ..
DF-170-181103-888_2529.11                  1
DF-200-192400-625_7557.13                  1
DF-200-192400-625_6304.14                  1
DF-170-181122-878_0223.4                   1
DF-170-181110-876_5210.10                  1
Name: count, Length: 476, dtype: int64

In [110]:
torch.tensor(data_list[20]['lpp_1943.610']).shape

torch.Size([11, 4096])

In [154]:
data_list[1]['lpp_1943.12']

[[-0.27480408549308777,
  0.714698314666748,
  -4.059543132781982,
  1.2532035112380981,
  -2.112856864929199,
  -1.3800097703933716,
  -1.2238043546676636,
  3.35485577583313,
  -0.48253297805786133,
  0.05253693833947182,
  -0.7601242065429688,
  -0.06180340051651001,
  0.18914654850959778,
  1.029049038887024,
  -0.43090900778770447,
  2.9023690223693848,
  -0.23654034733772278,
  1.2979989051818848,
  -1.5577071905136108,
  1.2718422412872314,
  -0.9503739476203918,
  -3.230721950531006,
  0.6173940896987915,
  1.5127170085906982,
  -0.3876633644104004,
  -0.6552905440330505,
  1.552248477935791,
  -5.221429347991943,
  -1.179642677307129,
  2.906890392303467,
  2.0420074462890625,
  0.4639958441257477,
  -1.3114439249038696,
  -2.7852489948272705,
  2.4857192039489746,
  1.380673885345459,
  2.915138006210327,
  1.283930778503418,
  1.2672699689865112,
  -1.5676358938217163,
  -1.0637099742889404,
  0.7816864848136902,
  1.2741726636886597,
  0.42820972204208374,
  3.9566335678100586,
  0.8976457715034485,
  0.3922257125377655,
  -0.4078632593154907,
  2.4145326614379883,
  -1.7036104202270508,
  0.6882060766220093,
  1.977718472480774,
  1.397809624671936,
  -1.0133169889450073,
  -0.7481048107147217,
  -1.6965701580047607,
  0.6575384140014648,
  -0.7634338140487671,
  -0.32581135630607605,
  0.31040894985198975,
  2.9249448776245117,
  -1.777312994003296,
  -0.6395555138587952,
  0.03280041739344597,
  -1.1621954441070557,
  0.15989373624324799,
  -1.0025132894515991,
  -2.329380750656128,
  -1.8742156028747559,
  0.4910193085670471,
  -1.7193650007247925,
  -0.42313578724861145,
  0.9436277151107788,
  -0.38342633843421936,
  -2.0647754669189453,
  -1.9663647413253784,
  0.6102633476257324,
  1.2618083953857422,
  -1.2764286994934082,
  -0.15039636194705963,
  -5.486393928527832,
  1.129042148590088,
  -1.0920071601867676,
  -0.5941694378852844,
  0.44372668862342834,
  2.601774215698242,
  -0.10900198668241501,
  -0.12561941146850586,
  -2.0839602947235107,
  0.9714542627334595,
  -2.120804786682129,
  0.8750489950180054,
  0.542384147644043,
  -0.629140317440033,
  -0.3923563063144684,
  1.2226941585540771,
  -0.7304056882858276,
  1.2349839210510254,
  0.022089410573244095,
  1.6328785419464111,
  2.9592959880828857,
  -4.2007856369018555,
  -0.2362358570098877,
  -0.34442779421806335,
  1.0893118381500244,
  0.32346540689468384,
  -0.5106751918792725,
  1.6092760562896729,
  -2.6244351863861084,
  0.8819237947463989,
  1.874252438545227,
  -2.8039844036102295,
  -1.9190177917480469,
  0.9352467656135559,
  -1.7664399147033691,
  1.6369017362594604,
  -0.9386277794837952,
  -0.6688017845153809,
  -0.6981649994850159,
  -0.7552498579025269,
  0.6151368618011475,
  -3.3346478939056396,
  -0.4303712844848633,
  -1.013358473777771,
  -2.1591649055480957,
  0.9917755722999573,
  -0.2973513603210449,
  -1.3494879007339478,
  -2.801384687423706,
  -1.2652099132537842,
  0.8810536861419678,
  1.4166151285171509,
  0.6618219614028931,
  -7.6378679275512695,
  -0.9718533754348755,
  1.7561959028244019,
  -0.7285935878753662,
  3.5781099796295166,
  0.3689734935760498,
  0.07529030740261078,
  -1.2980211973190308,
  -0.9428951740264893,
  2.2453596591949463,
  -0.7142202258110046,
  0.38444554805755615,
  -0.8583425283432007,
  0.5888993740081787,
  -0.4614379107952118,
  -1.2163591384887695,
  1.5688225030899048,
  2.283484697341919,
  -1.2041796445846558,
  -0.6878928542137146,
  1.5898237228393555,
  -0.6122999787330627,
  1.9061028957366943,
  -2.543612480163574,
  -0.2879753112792969,
  -0.23752832412719727,
  -0.08907503634691238,
  1.0140529870986938,
  -0.6819058060646057,
  0.08787792921066284,
  -2.24924373626709,
  2.8878374099731445,
  0.6228100657463074,
  -1.5723990201950073,
  -0.14429403841495514,
  0.8695541620254517,
  -0.2694057822227478,
  -2.537480115890503,
  1.2722476720809937,
  2.7753310203552246,
  0.44309186935424805,
  2.5217926502227783,
  1.9808681011199951,
  3.2952370643615723,
  1.2404931783676147,
  0.44978392124176025,
  0.5385643243789673,
  2.859881639480591,
  -1.3001710176467896,
  -0.24974003434181213,
  -4.557772159576416,
  19.815235137939453,
  0.7017218470573425,
  -2.4368555545806885,
  -0.9186910390853882,
  0.5220355987548828,
  0.587164044380188,
  0.17929518222808838,
  -0.5196769833564758,
  -2.5893332958221436,
  0.8581842184066772,
  -1.1987313032150269,
  -0.6795840859413147,
  -1.4574048519134521,
  -0.6284409761428833,
  -2.531049966812134,
  2.0362954139709473,
  1.946724534034729,
  2.6385793685913086,
  -0.7154812216758728,
  1.1509958505630493,
  -0.9367712736129761,
  -0.6400362253189087,
  -0.9779939651489258,
  0.39854946732521057,
  1.3936532735824585,
  3.085249185562134,
  1.226811408996582,
  3.3764450550079346,
  -0.8946683406829834,
  1.1922855377197266,
  -2.2381060123443604,
  -3.205811023712158,
  0.09303464740514755,
  -4.116777420043945,
  1.0732725858688354,
  0.28304973244667053,
  -1.4216787815093994,
  -1.4846268892288208,
  0.27462896704673767,
  -0.5477489233016968,
  -2.7511796951293945,
  -2.740729808807373,
  0.8022204041481018,
  -2.2202324867248535,
  3.0631980895996094,
  3.600545644760132,
  -2.5018179416656494,
  -0.295536607503891,
  -1.487342119216919,
  -1.0425840616226196,
  -0.6978897452354431,
  -3.179365634918213,
  -5.735208511352539,
  1.266861081123352,
  1.7425613403320312,
  0.4148128926753998,
  1.018457293510437,
  1.4716347455978394,
  3.911125421524048,
  4.928009033203125,
  2.5363943576812744,
  0.6637214422225952,
  -2.2795276641845703,
  1.3224992752075195,
  1.919685959815979,
  0.3209144175052643,
  -0.7105432152748108,
  -1.006698489189148,
  -0.6072665452957153,
  3.696166753768921,
  -1.0536352396011353,
  3.1554291248321533,
  0.5968800783157349,
  0.2651621997356415,
  0.3155610263347626,
  -0.7163234353065491,
  2.7354650497436523,
  -0.6847797632217407,
  1.2336777448654175,
  -0.14727406203746796,
  -1.1843459606170654,
  -3.4422664642333984,
  -0.8931748867034912,
  -2.0466208457946777,
  3.505344867706299,
  0.6272394061088562,
  0.5714995861053467,
  -2.121009588241577,
  -0.272312194108963,
  -1.4646003246307373,
  -1.1651970148086548,
  -1.470866322517395,
  0.9492735266685486,
  -2.3354806900024414,
  1.6378498077392578,
  -1.078452229499817,
  -2.8865432739257812,
  -1.0275530815124512,
  4.258150100708008,
  2.049327850341797,
  1.3258918523788452,
  -1.4410243034362793,
  1.2750248908996582,
  1.9781455993652344,
  -1.9133381843566895,
  5.6993513107299805,
  3.387239933013916,
  1.67840576171875,
  -8.367298126220703,
  -5.874081611633301,
  -4.3442535400390625,
  -0.3460523188114166,
  0.9530975222587585,
  -1.1659077405929565,
  -0.4753563702106476,
  2.937481641769409,
  -0.7490142583847046,
  -0.8264985680580139,
  -3.1145148277282715,
  0.3147881031036377,
  -1.313740849494934,
  1.9627137184143066,
  -2.827789545059204,
  0.40928545594215393,
  0.0937882512807846,
  -1.0777084827423096,
  0.49253493547439575,
  2.6782588958740234,
  -0.9470644593238831,
  1.2486827373504639,
  -1.0433446168899536,
  1.888104796409607,
  0.4838172495365143,
  3.2024459838867188,
  0.1276022046804428,
  0.22043415904045105,
  9.247732162475586,
  -2.4061243534088135,
  -2.239468812942505,
  0.13915033638477325,
  3.1283183097839355,
  0.9988567233085632,
  0.20199447870254517,
  1.1616370677947998,
  -0.2991993725299835,
  0.006442304700613022,
  -3.1625497341156006,
  1.843760371208191,
  0.15173839032649994,
  3.336500883102417,
  0.10989736765623093,
  0.3207264542579651,
  0.05808113142848015,
  -0.24017436802387238,
  1.4381192922592163,
  -0.6290143132209778,
  0.9597848057746887,
  -0.20875246822834015,
  2.414391040802002,
  0.3406839966773987,
  2.571436643600464,
  2.3113632202148438,
  1.2635663747787476,
  -0.7058139443397522,
  -0.7239899635314941,
  4.972445487976074,
  1.5085586309432983,
  -1.8623006343841553,
  2.818647861480713,
  -0.17195867002010345,
  1.3311045169830322,
  3.0427491664886475,
  0.5447437763214111,
  0.11772830784320831,
  0.6939647793769836,
  3.4034454822540283,
  -0.8917972445487976,
  1.372106671333313,
  1.5386908054351807,
  1.1113777160644531,
  -1.6400794982910156,
  -3.8480350971221924,
  -3.4490036964416504,
  -0.33055970072746277,
  0.9150548577308655,
  -0.9029871225357056,
  1.0891139507293701,
  -1.9549639225006104,
  -2.1841254234313965,
  2.850114583969116,
  1.5725144147872925,
  1.6248890161514282,
  -1.1993035078048706,
  0.5425627827644348,
  1.621960163116455,
  0.24010810256004333,
  -2.3430206775665283,
  -1.65537428855896,
  -0.21693941950798035,
  -0.285580039024353,
  4.180193901062012,
  -1.839896321296692,
  -1.2876110076904297,
  -5.678416728973389,
  -3.5030171871185303,
  -0.4185640513896942,
  0.18514259159564972,
  -0.936411440372467,
  -2.980395793914795,
  0.6138514876365662,
  -1.0602726936340332,
  -1.2665671110153198,
  -0.03990346938371658,
  4.492704391479492,
  -1.9635924100875854,
  0.9809767603874207,
  0.6625669002532959,
  -3.152301788330078,
  0.9057029485702515,
  0.35167166590690613,
  -2.1615984439849854,
  -1.2098941802978516,
  11.296927452087402,
  -2.5833160877227783,
  2.304187297821045,
  -0.5625783205032349,
  1.0476436614990234,
  -0.18123555183410645,
  0.518042802810669,
  0.13736553490161896,
  -0.5371241569519043,
  1.4705195426940918,
  1.8284738063812256,
  1.1191701889038086,
  -0.1278763860464096,
  -0.5679819583892822,
  2.805321216583252,
  -0.5853899717330933,
  0.4358751177787781,
  0.5938522219657898,
  1.19789719581604,
  1.8995541334152222,
  -0.6747822761535645,
  0.2160148173570633,
  -2.702026128768921,
  -0.8526703119277954,
  -0.6770297288894653,
  -2.6588780879974365,
  -3.377046585083008,
  1.8050615787506104,
  -1.9572818279266357,
  -3.853853464126587,
  1.2682219743728638,
  -0.9484652876853943,
  -2.213369131088257,
  -0.30120569467544556,
  -0.0017594225937500596,
  -0.15001288056373596,
  0.2636980712413788,
  0.16898378729820251,
  -2.6970202922821045,
  1.5494518280029297,
  0.8750674724578857,
  0.9089947938919067,
  -0.05428041145205498,
  0.7985725998878479,
  -0.47696900367736816,
  1.8973286151885986,
  -0.9487910270690918,
  -1.3639531135559082,
  2.327995777130127,
  -3.5518507957458496,
  1.758400797843933,
  -4.638742923736572,
  -0.09150200337171555,
  2.1925852298736572,
  -2.088258981704712,
  -2.1842899322509766,
  0.46113643050193787,
  -1.0345840454101562,
  -0.304478257894516,
  1.5786912441253662,
  2.4397783279418945,
  0.6452187895774841,
  -0.21243879199028015,
  0.8402087688446045,
  0.9452163577079773,
  -2.2704925537109375,
  -0.1240222156047821,
  0.923691987991333,
  0.8427539467811584,
  0.41069644689559937,
  1.7618963718414307,
  0.0749322846531868,
  -1.790164589881897,
  -0.837775468826294,
  -2.355271577835083,
  -0.310721755027771,
  -1.2977242469787598,
  0.35060954093933105,
  0.18606655299663544,
  0.7937211394309998,
  -1.045441746711731,
  2.2532689571380615,
  -0.7178946137428284,
  1.8428752422332764,
  -1.4814324378967285,
  2.7011828422546387,
  1.717814564704895,
  2.1041176319122314,
  1.1441398859024048,
  0.33537957072257996,
  -1.3180433511734009,
  -3.78434419631958,
  -0.23177501559257507,
  -0.5517368316650391,
  0.005769323091953993,
  -0.30522796511650085,
  -2.9661903381347656,
  2.7953977584838867,
  6.6934990882873535,
  1.1226321458816528,
  -1.9846299886703491,
  1.0668727159500122,
  -3.723581075668335,
  -1.5540343523025513,
  3.9404258728027344,
  -1.8769450187683105,
  2.7412643432617188,
  2.5732944011688232,
  -0.4645370543003082,
  0.0252325851470232,
  0.6937333345413208,
  0.054764214903116226,
  8.571534156799316,
  0.7842950820922852,
  1.1177527904510498,
  2.246213674545288,
  2.7499570846557617,
  -1.7533583641052246,
  -0.13097642362117767,
  -1.5283443927764893,
  -0.40353018045425415,
  -1.4695762395858765,
  -0.5837364792823792,
  1.3704301118850708,
  -0.4785105288028717,
  0.7862293720245361,
  1.9847875833511353,
  0.2908079922199249,
  -2.4768474102020264,
  0.2056305706501007,
  -1.0856190919876099,
  -3.0995123386383057,
  1.3147729635238647,
  -0.6847460865974426,
  1.3984977006912231,
  -0.49827805161476135,
  1.234216332435608,
  -3.3865394592285156,
  1.3972371816635132,
  2.738903522491455,
  0.18988797068595886,
  -1.5655630826950073,
  -0.2049587517976761,
  -0.4133659303188324,
  0.08097787201404572,
  -4.27148962020874,
  -0.5069423317909241,
  0.4464307725429535,
  3.40541410446167,
  0.6535347700119019,
  0.45604178309440613,
  -0.0434226468205452,
  -2.063372850418091,
  0.4562237560749054,
  0.37281274795532227,
  -0.25439581274986267,
  0.5865747928619385,
  4.089028835296631,
  -0.051938172429800034,
  -1.0212090015411377,
  -4.019395351409912,
  -1.4895524978637695,
  0.22631332278251648,
  1.0100464820861816,
  -2.1255810260772705,
  2.194399118423462,
  -1.3929286003112793,
  -0.8543236255645752,
  0.9942687153816223,
  -1.7951408624649048,
  4.179544925689697,
  -0.4778536558151245,
  3.178419589996338,
  0.5197647213935852,
  -0.13175909221172333,
  -1.1882877349853516,
  1.2598934173583984,
  -1.2362070083618164,
  1.2079107761383057,
  1.4037643671035767,
  0.5392906069755554,
  -0.17220446467399597,
  -1.2764021158218384,
  2.964949369430542,
  0.4334886074066162,
  0.738103985786438,
  -0.8329598903656006,
  -2.525308609008789,
  1.5873899459838867,
  0.9684008955955505,
  0.8788133859634399,
  -3.5426721572875977,
  2.4953505992889404,
  1.0366677045822144,
  0.8368746042251587,
  0.3222980797290802,
  1.4303795099258423,
  -0.45199593901634216,
  -1.8275740146636963,
  0.4826483130455017,
  -0.9406582713127136,
  0.3684968948364258,
  -2.17740535736084,
  -0.16020432114601135,
  -4.868113994598389,
  -6.636192798614502,
  0.10879352688789368,
  0.7996327877044678,
  -2.2346866130828857,
  -2.6879663467407227,
  -1.6936622858047485,
  0.26177531480789185,
  -1.453270673751831,
  0.21854263544082642,
  2.0330750942230225,
  1.3701870441436768,
  2.2851107120513916,
  -1.203291654586792,
  -3.5981404781341553,
  -2.813033103942871,
  -1.1626842021942139,
  -0.6595225930213928,
  -0.6436315178871155,
  -1.0362606048583984,
  0.4192149043083191,
  -4.227247714996338,
  -0.5040766000747681,
  0.7815327048301697,
  -0.24461030960083008,
  0.08925744146108627,
  -2.1453845500946045,
  -0.41412460803985596,
  -0.6621700525283813,
  -2.132265329360962,
  -0.2071610391139984,
  14.228044509887695,
  -4.629385948181152,
  2.037207841873169,
  -0.37358158826828003,
  3.4985203742980957,
  4.079298973083496,
  0.6311918497085571,
  -1.8567569255828857,
  1.6415446996688843,
  -1.2195967435836792,
  1.400513768196106,
  -0.0961155816912651,
  1.7849810123443604,
  1.7332448959350586,
  1.4498028755187988,
  1.2153911590576172,
  -2.438227891921997,
  2.9158453941345215,
  -0.09249468892812729,
  -1.1133801937103271,
  -0.6267893314361572,
  0.2152661234140396,
  -2.0818493366241455,
  -1.2111709117889404,
  1.9657338857650757,
  -0.07154787331819534,
  -2.034135580062866,
  -1.7483549118041992,
  -1.9639060497283936,
  3.7330820560455322,
  2.0083324909210205,
  0.1819925755262375,
  -1.141797661781311,
  -2.1773104667663574,
  -1.3118455410003662,
  3.8037049770355225,
  -0.3941402733325958,
  0.8127487897872925,
  0.7230522632598877,
  1.7510550022125244,
  1.158233880996704,
  -0.033888425678014755,
  -1.4941132068634033,
  0.10327517986297607,
  -1.6756808757781982,
  2.506687879562378,
  3.4714739322662354,
  -1.287414789199829,
  1.7418432235717773,
  1.4391324520111084,
  -0.5122014880180359,
  -0.3525784909725189,
  3.0640456676483154,
  -0.4123992323875427,
  -0.9265596270561218,
  -0.17007534205913544,
  -1.1656155586242676,
  0.2015870213508606,
  0.7867968082427979,
  -0.1885146200656891,
  -3.2263519763946533,
  1.901569128036499,
  1.171291470527649,
  -1.7692210674285889,
  -0.18858785927295685,
  0.9480089545249939,
  -0.19604434072971344,
  -2.2737600803375244,
  -3.9396517276763916,
  -0.7060889601707458,
  -0.15708141028881073,
  3.4898829460144043,
  3.568417549133301,
  -1.032702088356018,
  2.74084210395813,
  2.072628974914551,
  -0.11887725442647934,
  0.6849455237388611,
  -1.9424464702606201,
  1.7368013858795166,
  1.092820405960083,
  2.0122010707855225,
  1.0563908815383911,
  1.5786242485046387,
  0.26933202147483826,
  3.4280967712402344,
  -1.3838393688201904,
  -0.6171784400939941,
  -1.068922758102417,
  0.6922043561935425,
  -0.6968770623207092,
  -1.4962670803070068,
  -1.6353398561477661,
  1.1405366659164429,
  0.7389647960662842,
  2.305685043334961,
  4.0954365730285645,
  0.14920678734779358,
  -1.188002586364746,
  0.4746797978878021,
  0.7443030476570129,
  -2.5947930812835693,
  -0.31244638562202454,
  -0.14954447746276855,
  -1.3138058185577393,
  0.29759421944618225,
  3.0172879695892334,
  0.7364268898963928,
  0.9971946477890015,
  0.08321654051542282,
  1.4859591722488403,
  -1.1755311489105225,
  -0.31154465675354004,
  -2.8726346492767334,
  -0.388579785823822,
  -2.7622156143188477,
  -0.11224304139614105,
  3.712012767791748,
  -0.8223603367805481,
  -2.3204104900360107,
  3.553694009780884,
  -0.7918153405189514,
  0.34457144141197205,
  -1.6627696752548218,
  2.6384830474853516,
  0.11375772207975388,
  1.5851961374282837,
  0.5977694988250732,
  0.5835884809494019,
  1.367234706878662,
  1.5355629920959473,
  -1.147557020187378,
  -2.118955135345459,
  2.597752571105957,
  -0.007255816366523504,
  -0.2224123179912567,
  -0.06741031259298325,
  -1.3514961004257202,
  -0.4941631257534027,
  -0.8429163098335266,
  -1.1054273843765259,
  20.43865966796875,
  -0.4663153290748596,
  1.389047622680664,
  -0.3511364758014679,
  -1.3256982564926147,
  3.0020391941070557,
  1.273021936416626,
  3.72182559967041,
  -0.019888272508978844,
  -0.19020627439022064,
  0.0770418643951416,
  -3.116150140762329,
  1.7072701454162598,
  1.976420283317566,
  -1.0358625650405884,
  -2.1335513591766357,
  -1.3327443599700928,
  -2.5103838443756104,
  -2.0504415035247803,
  -1.5542346239089966,
  -3.4787795543670654,
  -3.394965887069702,
  -1.7749848365783691,
  0.9217070937156677,
  0.540107250213623,
  0.8143264055252075,
  -1.3482921123504639,
  2.4946556091308594,
  -2.0114595890045166,
  -0.9063048958778381,
  2.9067344665527344,
  -0.4512343108654022,
  1.511448860168457,
  -0.9942364692687988,
  0.2038291096687317,
  -0.7887070178985596,
  2.3716750144958496,
  -1.0177901983261108,
  -0.818496584892273,
  -3.675111770629883,
  2.2642579078674316,
  -1.2963829040527344,
  0.4218001961708069,
  -0.17071907222270966,
  -1.1924927234649658,
  2.3261163234710693,
  0.48910704255104065,
  -1.8580710887908936,
  0.08792244642972946,
  -1.543304681777954,
  2.359863519668579,
  -0.8463187217712402,
  1.2293378114700317,
  2.310389995574951,
  -1.5096250772476196,
  0.9070609211921692,
  -0.750148594379425,
  1.0663821697235107,
  -0.09065882116556168,
  0.8537731766700745,
  0.4302712678909302,
  -0.4132606089115143,
  0.33840593695640564,
  0.018385225906968117,
  0.17290298640727997,
  -5.004675388336182,
  1.641074538230896,
  0.28942710161209106,
  0.6486342549324036,
  -1.3824511766433716,
  0.5324597358703613,
  0.2799715995788574,
  -0.88509202003479,
  0.23348043859004974,
  -0.38804954290390015,
  -0.2560275197029114,
  1.9106040000915527,
  2.0697689056396484,
  1.2239701747894287,
  1.6953985691070557,
  -1.114680528640747,
  0.6362297534942627,
  -0.3615305721759796,
  -2.2888526916503906,
  -0.031126897782087326,
  2.2728748321533203,
  2.7126452922821045,
  -0.8878664970397949,
  2.5300114154815674,
  2.076439142227173,
  -0.6934155225753784,
  -2.73496150970459,
  0.25711822509765625,
  2.425100564956665,
  2.0721089839935303,
  0.7420285940170288,
  -0.012139523401856422,
  -1.240673303604126,
  -0.32946348190307617,
  0.3728469908237457,
  1.867383599281311,
  3.220954418182373,
  0.517264723777771,
  2.4604148864746094,
  2.488877773284912,
  -0.22937403619289398,
  0.22043439745903015,
  7.160943508148193,
  3.2960543632507324,

In [155]:
df[df['id'] == 'lpp_1943.12']

,id,context,sentence,graph,variable_name,predicate,broad_aspect_1,broad_aspect_2,broad_aspect_3,broad_aspect_4,broad_aspect_5,adjudicated,second_choice_adjudicated,compare,alignment,flag,reason_for_flag
1,lpp_1943.12,"But they answered : "" Frighten ?","Why should any one be frightened by a hat ? """,(s12s / say-91\n :ARG0 (s12p2 / person)\n...,s12s,say-91,none,performance,performance,NaN,NaN,performance,NaN,False,s12s: 0-0; s12p2: 0-0; s12f: 6-6; s12h: 9-9; s...,False,NaN
2,lpp_1943.12,"But they answered : "" Frighten ?","Why should any one be frightened by a hat ? """,(s12s / say-91\n :ARG0 (s12p2 / person)\n...,s12f,frighten-01,state,state,NaN,NaN,NaN,state,NaN,True,s12s: 0-0; s12p2: 0-0; s12f: 6-6; s12h: 9-9; s...,False,NaN

In [105]:
df[df['id'] == 'lpp_1943.610']

,id,context,sentence,graph,variable_name,predicate,broad_aspect_1,broad_aspect_2,broad_aspect_3,broad_aspect_4,broad_aspect_5,adjudicated,second_choice_adjudicated,compare,alignment,flag,reason_for_flag
53,lpp_1943.610,""" Good morning , "" said the little prince .",""" That is a queer hat you are wearing . """,(s610h2 / hat\n :mod (s610q2 / queer)\n...,s610w2,wear-01,state,state,NaN,NaN,NaN,state,NaN,True,s610h2: 6-6; s610q2: 5-5; s610t2: 2-2; s610w2:...,False,NaN

In [ ]:
df[df['id'] == 'lpp_1943.610'].iloc[0]['alignment']

's610h2: 6-6; s610q2: 5-5; s610t2: 2-2; s610w2: 9-9'

In [58]:
print(df[df['id'] == 'lpp_1943.610'].iloc[0]['graph'])

(s610h2 / hat
        :mod (s610q2 / queer)
        :domain (s610t2 / that)
        :ARG1-of (s610w2 / wear-01))

In [59]:
g = penman.decode(df[df['id'] == 'lpp_1943.610'].iloc[0]['graph'])

In [66]:
g.instances()

[Instance(source='s610h2', role=':instance', target='hat'),
 Instance(source='s610q2', role=':instance', target='queer'),
 Instance(source='s610t2', role=':instance', target='that'),
 Instance(source='s610w2', role=':instance', target='wear-01')]

In [65]:
g.triples

[('s610h2', ':instance', 'hat'),
 ('s610h2', ':mod', 's610q2'),
 ('s610q2', ':instance', 'queer'),
 ('s610h2', ':domain', 's610t2'),
 ('s610t2', ':instance', 'that'),
 ('s610w2', ':ARG1', 's610h2'),
 ('s610w2', ':instance', 'wear-01')]

In [63]:
g.edges()

[Edge(source='s610h2', role=':mod', target='s610q2'),
 Edge(source='s610h2', role=':domain', target='s610t2'),
 Edge(source='s610w2', role=':ARG1', target='s610h2')]

In [188]:
df.head()

,id,context,sentence,graph,variable_name,predicate,broad_aspect_1,broad_aspect_2,broad_aspect_3,broad_aspect_4,broad_aspect_5,adjudicated,second_choice_adjudicated,compare,alignment,flag,reason_for_flag
0,lpp_1943.1,NaN,Chapter 1 .,(s1p / publication-91\n :ARG1 (s1c / chapt...,s1p,publication-91,none,none,NaN,NaN,NaN,none,NaN,True,s1p: 0-0; s1c: 1-1; s1o: 2-2; s1t: 0-0,False,NaN
1,lpp_1943.12,"But they answered : "" Frighten ?","Why should any one be frightened by a hat ? """,(s12s / say-91\n :ARG0 (s12p2 / person)\n...,s12s,say-91,none,performance,performance,NaN,NaN,performance,NaN,False,s12s: 0-0; s12p2: 0-0; s12f: 6-6; s12h: 9-9; s...,False,NaN
2,lpp_1943.12,"But they answered : "" Frighten ?","Why should any one be frightened by a hat ? """,(s12s / say-91\n :ARG0 (s12p2 / person)\n...,s12f,frighten-01,state,state,NaN,NaN,NaN,state,NaN,True,s12s: 0-0; s12p2: 0-0; s12f: 6-6; s12h: 9-9; s...,False,NaN
3,lpp_1943.21,Grown - ups never understand anything by thems...,"So then I chose another profession , and learn...",(s21h / have-reason-91\n :ARG1 (s21a / an...,s21h,have-reason-91,none,none,NaN,NaN,NaN,none,NaN,True,s21h: 0-0; s21a: 8-8; s21c: 4-4; s21i: 3-3; s2...,False,NaN
4,lpp_1943.21,Grown - ups never understand anything by thems...,"So then I chose another profession , and learn...",(s21h / have-reason-91\n :ARG1 (s21a / an...,s21c,choose-01,performance,performance,NaN,NaN,NaN,performance,NaN,True,s21h: 0-0; s21a: 8-8; s21c: 4-4; s21i: 3-3; s2...,False,NaN

In [189]:
i = 0
for d in data_list:
    df_id = list(d.keys())[0]

    df_for_id = df[df['id'] == df_id]

    i += len(df_for_id)

print(i)

1473

In [104]:
import torch
from torch_geometric.data import Data, Dataset

In [ ]:
def get_mapping_dict(mapping):
  rec = {}

  for i in mapping.split(";"):
    key = i.split(":")[0].strip()
    value = i.split(":")[1].strip()

    start = int(value.split("-")[0])
    end = int(value.split("-")[1])

    rec[key] = [start, end]
  
  return rec

def create_graph_object(graph_str, target_node, var_mapping, embedding, label):
  print("graph_str")
  print(graph_str)
  penman_graph = penman.decode(graph_str)

  instances = penman_graph.instances()
  edges = penman_graph.edges()

  node2index = {}
  index2node = {}

  mapping_rec = get_mapping_dict(var_mapping)

  node_data = torch.tensor([])
  curr_index = 0

  target_index = -1
  edges_rec = []
  for i in range(len(instances)):
    print("instance", instances[i])
    s = instances[i].source

    start, end = mapping_rec.get(s, [0,0])

    if start != 0:
      start -= 1
      k = embedding[start:end]
      node_data = torch.cat((node_data, torch.sum(k, dim=0).unsqueeze(0)))
    else:
      node_data = torch.cat((node_data, torch.sum(embedding, dim=0).unsqueeze(0)))

    node2index[s] = curr_index
    curr_index += 1

    if s == target_node:
      target_index = curr_index - 1
  
  for e in edges:
    print(e)
    source = e.source
    target = e.target
    edges_rec.append([node2index[source], node2index[target]])
    edges_rec.append([node2index[target], node2index[source]])

  # edges_rec.append([target_index, node2index['aspect']])
  edges_data = torch.tensor(edges_rec).t().contiguous()
  print("node2index", node2index)
  return Data(x=node_data, edge_index=edges_data, y=torch.tensor(label), target_node=torch.tensor(node2index[target_node]))

In [178]:
transform = RemoveDuplicatedEdges()

In [174]:
df[df['id'] == 'lpp_1943.12']

,id,context,sentence,graph,variable_name,predicate,broad_aspect_1,broad_aspect_2,broad_aspect_3,broad_aspect_4,broad_aspect_5,adjudicated,second_choice_adjudicated,compare,alignment,flag,reason_for_flag
1,lpp_1943.12,"But they answered : "" Frighten ?","Why should any one be frightened by a hat ? """,(s12s / say-91\n :ARG0 (s12p2 / person)\n...,s12s,say-91,none,performance,performance,NaN,NaN,performance,NaN,False,s12s: 0-0; s12p2: 0-0; s12f: 6-6; s12h: 9-9; s...,False,NaN
2,lpp_1943.12,"But they answered : "" Frighten ?","Why should any one be frightened by a hat ? """,(s12s / say-91\n :ARG0 (s12p2 / person)\n...,s12f,frighten-01,state,state,NaN,NaN,NaN,state,NaN,True,s12s: 0-0; s12p2: 0-0; s12f: 6-6; s12h: 9-9; s...,False,NaN

In [175]:
df[df['id'] == 'lpp_1943.12'].iloc[0]['alignment']

's12s: 0-0; s12p2: 0-0; s12f: 6-6; s12h: 9-9; s12a: 3-3; s12u: 1-1; s12s: 11-11; s12p3: 0-0'

In [176]:
graph_py = create_graph_object(df[df['id'] == 'lpp_1943.12'].iloc[0]['graph'], "s12s", df[df['id'] == 'lpp_1943.12'].iloc[0]['alignment'], "", torch.tensor(data_list[1]['lpp_1943.12']), 0)

graph_str
(s12s / say-91
      :ARG0 (s12p2 / person)
      :ARG1 (s12f / frighten-01
                  :ARG0 (s12h / hat)
                  :ARG1 (s12p / person
                              :mod (s12a / any)
                              :refer-person 3rd
                              :refer-number singular)
                  :reason (s12u / umr-unknown)
                  :quote s12s)
      :ARG2 (s12p3 / person))
instance Instance(source='s12s', role=':instance', target='say-91')
instance Instance(source='s12p2', role=':instance', target='person')
instance Instance(source='s12f', role=':instance', target='frighten-01')
instance Instance(source='s12h', role=':instance', target='hat')
instance Instance(source='s12p', role=':instance', target='person')
instance Instance(source='s12a', role=':instance', target='any')
instance Instance(source='s12u', role=':instance', target='umr-unknown')
instance Instance(source='s12p3', role=':instance', target='person')
Edge(source='s12s', role=':ARG0', target='s12p2')
Edge(source='s12s', role=':ARG1', target='s12f')
Edge(source='s12f', role=':ARG0', target='s12h')
Edge(source='s12f', role=':ARG1', target='s12p')
Edge(source='s12p', role=':mod', target='s12a')
Edge(source='s12f', role=':reason', target='s12u')
Edge(source='s12f', role=':quote', target='s12s')
Edge(source='s12s', role=':ARG2', target='s12p3')
node2index {'s12s': 0, 's12p2': 1, 's12f': 2, 's12h': 3, 's12p': 4, 's12a': 5, 's12u': 6, 's12p3': 7}

In [168]:
graph_py.edge_index

tensor([[0, 1, 0, 2, 2, 3, 2, 4, 4, 5, 2, 6, 2, 0, 0, 7],
        [1, 0, 2, 0, 3, 2, 4, 2, 5, 4, 6, 2, 0, 2, 7, 0]])

In [179]:
graph_py = transform(graph_py)

In [181]:
graph_py

Data(x=[8, 4096], edge_index=[2, 14], y=0, target_node=0)

In [180]:
graph_py.edge_index

tensor([[0, 0, 0, 1, 2, 2, 2, 2, 3, 4, 4, 5, 6, 7],
        [1, 2, 7, 0, 0, 3, 4, 6, 2, 2, 5, 4, 2, 0]])

In [ ]:
graph_py = create_graph_object(df[df['id'] == 'lpp_1943.610'].iloc[0]['graph'], "s610w2", df[df['id'] == 'lpp_1943.610'].iloc[0]['alignment'], "", torch.tensor(data_list[20]['lpp_1943.610']), 0)

In [145]:
graph_py = create_graph_object(df[df['id'] == 'lpp_1943.610'].iloc[0]['graph'], "s610w2", df[df['id'] == 'lpp_1943.610'].iloc[0]['alignment'], "", torch.tensor(data_list[20]['lpp_1943.610']), 0)

graph_str
(s610h2 / hat
        :mod (s610q2 / queer)
        :domain (s610t2 / that)
        :ARG1-of (s610w2 / wear-01))
node2index {'s610h2': 0, 's610q2': 1, 's610t2': 2, 's610w2': 3}

In [146]:
graph_py

Data(x=[4, 4096], edge_index=[2, 6], y=0, target_node=3)

In [152]:
graph_py.x.shape

torch.Size([4, 4096])

In [148]:
graph_py.edge_index

tensor([[0, 1, 0, 2, 3, 0],
        [1, 0, 2, 0, 0, 3]])

In [151]:
graph_py.is_undirected()

True

In [190]:
df[df['id'] == 'lpp_1943.748']

,id,context,sentence,graph,variable_name,predicate,broad_aspect_1,broad_aspect_2,broad_aspect_3,broad_aspect_4,broad_aspect_5,adjudicated,second_choice_adjudicated,compare,alignment,flag,reason_for_flag
299,lpp_1943.748,""" I myself own a flower , "" he continued his ...","I own three volcanoes , which I clean out ever...",(s748o / own-01\n :ARG0 (s748i / i)\n ...,s748o,own-01,state,state,NaN,NaN,NaN,state,NaN,True,"s748o: 2-2; s748i: 1-1,7-7,14-14; s748v: 4-4; ...",False,NaN
300,lpp_1943.748,""" I myself own a flower , "" he continued his ...","I own three volcanoes , which I clean out ever...",(s748o / own-01\n :ARG0 (s748i / i)\n ...,s748c,clean-out-03,habitual,habitual,NaN,NaN,NaN,habitual,NaN,True,"s748o: 2-2; s748i: 1-1,7-7,14-14; s748v: 4-4; ...",False,NaN
301,lpp_1943.748,""" I myself own a flower , "" he continued his ...","I own three volcanoes , which I clean out ever...",(s748o / own-01\n :ARG0 (s748i / i)\n ...,s748r,rate-entity-91,none,none,NaN,NaN,NaN,none,NaN,True,"s748o: 2-2; s748i: 1-1,7-7,14-14; s748v: 4-4; ...",False,NaN
302,lpp_1943.748,""" I myself own a flower , "" he continued his ...","I own three volcanoes , which I clean out ever...",(s748o / own-01\n :ARG0 (s748i / i)\n ...,s748m,mean-91,none,none,NaN,NaN,NaN,none,NaN,True,"s748o: 2-2; s748i: 1-1,7-7,14-14; s748v: 4-4; ...",False,NaN
303,lpp_1943.748,""" I myself own a flower , "" he continued his ...","I own three volcanoes , which I clean out ever...",(s748o / own-01\n :ARG0 (s748i / i)\n ...,s748c3,clean-out-03,habitual,habitual,NaN,NaN,NaN,habitual,NaN,True,"s748o: 2-2; s748i: 1-1,7-7,14-14; s748v: 4-4; ...",False,NaN
304,lpp_1943.748,""" I myself own a flower , "" he continued his ...","I own three volcanoes , which I clean out ever...",(s748o / own-01\n :ARG0 (s748i / i)\n ...,s748i2,include-91,none,none,NaN,NaN,NaN,none,NaN,True,"s748o: 2-2; s748i: 1-1,7-7,14-14; s748v: 4-4; ...",False,NaN
305,lpp_1943.748,""" I myself own a flower , "" he continued his ...","I own three volcanoes , which I clean out ever...",(s748o / own-01\n :ARG0 (s748i / i)\n ...,s748k,know-01,state,state,NaN,NaN,NaN,state,NaN,True,"s748o: 2-2; s748i: 1-1,7-7,14-14; s748v: 4-4; ...",False,NaN

In [191]:
df[df['id'] == 'lpp_1943.748'].iloc[0]['alignment']

's748o: 2-2; s748i: 1-1,7-7,14-14; s748v: 4-4; s748c: 8-9; s748r: 10-10; s748t: 0-0; s748w: 11-11; s748m: 13-13; s748c3: 16-17; s748v2: 0-0; s748e: 22-22; s748i2: 0-0; s748a: 15-15; s748k: 26-26; s748p: 24-24'

In [192]:
df[df['id'] == 'lpp_1943.748'].iloc[0]['sentence']

'I own three volcanoes , which I clean out every week ( for I also clean out the one that is extinct ; one never knows ) .'

In [193]:
print(df[df['id'] == 'lpp_1943.748'].iloc[0]['graph'])

(s748o / own-01
       :ARG0 (s748i / i)
       :ARG1 (s748v / volcano
                    :ARG1-of (s748c / clean-out-03
                                    :ARG0 s748i
                                    :frequency (s748r / rate-entity-91
                                                      :ARG3 (s748t / temporal-quantity
                                                                   :unit (s748w / week)
                                                                   :quant 1))
                                    :ARG1-of (s748m / mean-91
                                                    :ARG2 (s748c3 / clean-out-03
                                                                  :ARG0 s748i
                                                                  :ARG1 (s748v2 / volcano
                                                                                :mod (s748e / extinct)
                                                                                :ARG1-of (s748i2 / include-91
                                                                                                 :ARG2 s748v))
                                                                  :mod (s748a / also)
                                                                  :reason (s748k / know-01
                                                                                 :ARG0 (s748p / person
                                                                                              :refer-person 3rd
                                                                                              :refer-number singular)
                                                                                 :polarity -))))
                    :quant 3))

In [206]:
df[df['id'] == 'bolt-eng-DF-170-181105-8850361_0028.31']

,id,context,sentence,graph,variable_name,predicate,broad_aspect_1,broad_aspect_2,broad_aspect_3,broad_aspect_4,broad_aspect_5,adjudicated,second_choice_adjudicated,compare,alignment,flag,reason_for_flag
1221,bolt-eng-DF-170-181105-8850361_0028.31,This higher health spending is a function of d...,Atul Gawande wrote a much-discussed article on...,(s31a4 / and\n :op1 (s31w / write-01\n ...,s31w,write-01,NaN,performance,performance,NaN,NaN,performance,NaN,False,s31a4: 0-0\ns31w: 3-3\ns31p2: 0-0\ns31n2: 1-2\...,False,NaN
1222,bolt-eng-DF-170-181105-8850361_0028.31,This higher health spending is a function of d...,Atul Gawande wrote a much-discussed article on...,(s31a4 / and\n :op1 (s31w / write-01\n ...,s31d,discuss-01,NaN,habitual,habitual,NaN,NaN,habitual,NaN,False,s31a4: 0-0\ns31w: 3-3\ns31p2: 0-0\ns31n2: 1-2\...,False,NaN
1223,bolt-eng-DF-170-181105-8850361_0028.31,This higher health spending is a function of d...,Atul Gawande wrote a much-discussed article on...,(s31a4 / and\n :op1 (s31w / write-01\n ...,s31d2,describe-01,NaN,performance,none,none,NaN,none,NaN,False,s31a4: 0-0\ns31w: 3-3\ns31p2: 0-0\ns31n2: 1-2\...,False,NaN
1224,bolt-eng-DF-170-181105-8850361_0028.31,This higher health spending is a function of d...,Atul Gawande wrote a much-discussed article on...,(s31a4 / and\n :op1 (s31w / write-01\n ...,s31p3,publication-91,NaN,none,none,NaN,NaN,none,NaN,False,s31a4: 0-0\ns31w: 3-3\ns31p2: 0-0\ns31n2: 1-2\...,False,NaN
1225,bolt-eng-DF-170-181105-8850361_0028.31,This higher health spending is a function of d...,Atul Gawande wrote a much-discussed article on...,(s31a4 / and\n :op1 (s31w / write-01\n ...,s31c2,cost-01,NaN,none,none,NaN,NaN,none,NaN,False,s31a4: 0-0\ns31w: 3-3\ns31p2: 0-0\ns31n2: 1-2\...,False,NaN
1226,bolt-eng-DF-170-181105-8850361_0028.31,This higher health spending is a function of d...,Atul Gawande wrote a much-discussed article on...,(s31a4 / and\n :op1 (s31w / write-01\n ...,s31m2,mean-91,NaN,none,none,NaN,NaN,none,NaN,False,s31a4: 0-0\ns31w: 3-3\ns31p2: 0-0\ns31n2: 1-2\...,False,NaN
1227,bolt-eng-DF-170-181105-8850361_0028.31,This higher health spending is a function of d...,Atul Gawande wrote a much-discussed article on...,(s31a4 / and\n :op1 (s31w / write-01\n ...,s31p4,possible-01,NaN,none,none,NaN,NaN,none,NaN,False,s31a4: 0-0\ns31w: 3-3\ns31p2: 0-0\ns31n2: 1-2\...,False,NaN
1228,bolt-eng-DF-170-181105-8850361_0028.31,This higher health spending is a function of d...,Atul Gawande wrote a much-discussed article on...,(s31a4 / and\n :op1 (s31w / write-01\n ...,s31t2,teach-01,NaN,performance,state,performance,NaN,performance,NaN,False,s31a4: 0-0\ns31w: 3-3\ns31p2: 0-0\ns31n2: 1-2\...,True,Sentence is actually 2 sentences
1229,bolt-eng-DF-170-181105-8850361_0028.31,This higher health spending is a function of d...,Atul Gawande wrote a much-discussed article on...,(s31a4 / and\n :op1 (s31w / write-01\n ...,s31c3,care-03,none,none,NaN,NaN,NaN,none,NaN,True,s31a4: 0-0\ns31w: 3-3\ns31p2: 0-0\ns31n2: 1-2\...,False,NaN
1230,bolt-eng-DF-170-181105-8850361_0028.31,This higher health spending is a function of d...,Atul Gawande wrote a much-discussed article on...,(s31a4 / and\n :op1 (s31w / write-01\n ...,s31d3,disperse-01,NaN,process,process,NaN,NaN,process,NaN,False,s31a4: 0-0\ns31w: 3-3\ns31p2: 0-0\ns31n2: 1-2\...,False,NaN
1231,bolt-eng-DF-170-181105-8850361_0028.31,This higher health spending is a function of d...,Atul Gawande wrote a much-discussed article on...,(s31a4 / and\n :op1 (s31w / write-01\n ...,s31s2,spend-01,NaN,activity,process,process,NaN,process,NaN,False,s31a4: 0-0\ns31w: 3-3\ns31p2: 0-0\ns31n2: 1-2\...,False,NaN
1232,bolt-eng-DF-170-181105-8850361_0028.31,This higher health spending is a function of d...,Atul Gawande wrote a much-discussed article on...,(s31a4 / and\n :op1 (s31w / write-01\n ...,s31c4,care-03,NaN,none,none,NaN,NaN,none,NaN,False,s31a4: 0-0\ns31w: 3-3\ns31p2: 0-0\ns31n2: 1-2\...,False,NaN
1233,bolt-eng-DF-170-181105-8850361_0028.31,This higher health spending is a function of d...,Atul Gawande wrote a much-discussed article on...,(s31a4 / and\n :op1 (s31w / write-01\n ...,s31w3,wide-02,NaN,state,state,NaN,NaN,state,NaN,False,s31a4: 0-0\ns31w: 3-3\ns31p2: 0-0\ns31n2: 1-2\...,False,NaN
1234,bolt-eng-DF-170-181105-8850361_0028.31,This higher health spending is a function of d...,Atul Gawande wrote a much-discussed article on...,(s31a4 / and\n :op1 (s31w / write-01\n ...,s31p,possible-01,NaN,none,none,NaN,NaN,none,NaN,False,s31a4: 0-0\ns31w: 3-3\ns31p2: 0-0\ns31n2: 1-2\...,False,NaN
1235,bolt-eng-DF-170-181105-8850361_0028.31,This higher health spending is a function of d...,Atul Gawande wrote a much-discussed article on...,(s31a4 / and\n :op1 (s31w / write-01\n ...,s31e,explain-01,NaN,performance,state,state,NaN,state,NaN,False,s31a4: 0-0\ns31w: 3-3\ns31p2: 0-0\ns31n2: 1-2\...,False,NaN
1236,bolt-eng-DF-170-181105-8850361_0028.31,This higher health spending is a function of d...,Atul Gawande wrote a much-discussed article on...,(s31a4 / and\n :op1 (s31w / write-01\n ...,s31d4,differ-02,NaN,none,none,NaN,NaN,none,NaN,False,s31a4: 0-0\ns31w: 3-3\ns31p2: 0-0\ns31n2: 1-2\...,False,NaN
1237,bolt-eng-DF-170-181105-8850361_0028.31,This higher health spending is a function of d...,Atul Gawande wrote a much-discussed article on...,(s31a4 / and\n :op1 (s31w / write-01\n ...,s31d5,disperse-01,NaN,process,process,NaN,NaN,process,NaN,False,s31a4: 0-0\ns31w: 3-3\ns31p2: 0-0\ns31n2: 1-2\...,False,NaN
1238,bolt-eng-DF-170-181105-8850361_0028.31,This higher health spending is a function of d...,Atul Gawande wrote a much-discussed article on...,(s31a4 / and\n :op1 (s31w / write-01\n ...,s31i,include-91,NaN,none,none,NaN,NaN,none,NaN,False,s31a4: 0-0\ns31w: 3-3\ns31p2: 0-0\ns31n2: 1-2\...,False,NaN

In [207]:
get_mapping_dict(df[df['id'] == 'bolt-eng-DF-170-181105-8850361_0028.31'].iloc[0]['alignment'])

ValueError: invalid literal for int() with base 10: '0\ns31w'

In [209]:
df[df['id'] == 'bolt-eng-DF-170-181105-8850361_0028.31'].iloc[0]['alignment'].replace("\n", ";")

's31a4: 0-0;s31w: 3-3;s31p2: 0-0;s31n2: 1-2;s31a: 6-6;s31d: 5-5;s31m: 5-5;s31t: 8-8;s31d2: 0-0;s31p3: 0-0;s31c: 16-16;s31c2: 15-15;s31m2: 0-0;s31p4: 0-0;s31t2: 22-22;s31t3: 20-20;s31s: 0-0;s31n: 19-19;s31c3: 26-26;s31h: 25-25;s31w2: 23-23;s31m5: 0-0;s31n3: 11-13;s31a2: 0-0;s31d3: 31-31;s31s2: 35-35;s31c4: 34-34;s31m4: 33-33;s31g: 30-30;s31w3: 29-29;s31p: 38-38;s31e: 41-41;s31p5: 44-44;s31d4: 43-43;s31d5: 31-31;s31i: 0-0;s31a3: 39-39;'

In [210]:
df[df['id'] == 'bolt-eng-DF-201-185510-351190_0310.18'].iloc[0]['alignment']

's18c: \ns18s: \ns18i: \ns18a: \ns18p: \ns18t: \ns18y: \ns18i2: \ns18p2: \n'